project_id = "iqwmffxyagugixhuddcp"

[functions.vocab-ai-fill]
verify_jwt = false

[functions.analyze-sentence]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.generate-material]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.fix-vocab-kana]
verify_jwt = false
