-- Starter content templates + provision function
-- Generated by scripts/generate-starter-content.mjs

-- Template tables
CREATE TABLE IF NOT EXISTS public.starter_materials (
  starter_key text PRIMARY KEY,
  title text NOT NULL,
  content jsonb,
  level public.jlpt_level NOT NULL DEFAULT 'n5',
  category public.material_category NOT NULL,
  tags text[],
  vocabulary jsonb,
  grammar_notes jsonb,
  cultural_note text,
  indonesian_translation text,
  path public.learning_path NOT NULL DEFAULT 'jlpt_academic'
);

CREATE TABLE IF NOT EXISTS public.starter_vocab (
  starter_key text PRIMARY KEY,
  kanji text,
  kana text NOT NULL,
  meaning text NOT NULL,
  jlpt_level public.jlpt_level DEFAULT 'n5',
  tags text[]
);

ALTER TABLE public.starter_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.starter_vocab ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated read starter materials"
  ON public.starter_materials FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated read starter vocab"
  ON public.starter_vocab FOR SELECT TO authenticated USING (true);

-- Columns for user content linking
ALTER TABLE public.materials
  ADD COLUMN IF NOT EXISTS starter_key text;

ALTER TABLE public.learning_lessons
  ADD COLUMN IF NOT EXISTS starter_key text;

CREATE INDEX IF NOT EXISTS idx_materials_user_starter_key
  ON public.materials (user_id, starter_key)
  WHERE starter_key IS NOT NULL;

-- Seed templates (idempotent)
INSERT INTO public.starter_materials
  (starter_key, title, content, level, category, tags, vocabulary, grammar_notes, cultural_note, indonesian_translation, path)
VALUES
  (E'n5-hiragana-dasar', E'Hiragana Dasar — ひらがなの基礎', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"ひらがなは日本語の基本的な文字です。"}]},{"type":"paragraph","content":[{"type":"text","text":"あいうえお、かきくけこ、さしすせそ…と覚えましょう。"}]},{"type":"paragraph","content":[{"type":"text","text":"ひらがなは助詞や動詞の語尾にも使います。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'vocabulary'::public.material_category, ARRAY[E'hiragana', E'n5', E'starter']::text[], '[{"kanji":"あ","kana":"あ","meaning":"huruf a"},{"kanji":"い","kana":"い","meaning":"huruf i"},{"kanji":"う","kana":"う","meaning":"huruf u"}]'::jsonb, '[{"pattern":"あいうえお","explanation":"Baris pertama hiragana: a-i-u-e-o"}]'::jsonb, E'Hiragana adalah aksara fonetik asli Jepang, digunakan untuk kata asli Jepang dan furigana.', E'Hiragana terdiri dari 46 karakter dasar. Setiap karakter mewakili satu suku kata.', E'jlpt_academic'::public.learning_path),
  (E'n5-katakana-dasar', E'Katakana Dasar — カタカナの基礎', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"カタカナは外来語を書くときに使います。"}]},{"type":"paragraph","content":[{"type":"text","text":"例：コーヒー（coffee）、パソコン（computer）"}]},{"type":"paragraph","content":[{"type":"text","text":"カタカナの形はひらがなより角ばっています。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'vocabulary'::public.material_category, ARRAY[E'katakana', E'n5', E'starter']::text[], '[{"kanji":"ア","kana":"ア","meaning":"huruf a (katakana)"},{"kanji":"コーヒー","kana":"コーヒー","meaning":"kopi"},{"kanji":"パン","kana":"パン","meaning":"roti"}]'::jsonb, '[{"pattern":"外来語","explanation":"Kata asing ditulis dengan katakana"}]'::jsonb, E'Katakana dipakai untuk kata serapan dari bahasa asing.', E'Katakana digunakan untuk kata pinjaman seperti コーヒー (kopi) dan パン (roti).', E'jlpt_academic'::public.learning_path),
  (E'n5-salam-perkenalan', E'Salam & Perkenalan — あいさつ', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"はじめまして。マイクと申します。"}]},{"type":"paragraph","content":[{"type":"text","text":"アメリカから来ました。どうぞよろしくお願いします。"}]},{"type":"paragraph","content":[{"type":"text","text":"おはようございます。こんにちは。こんばんは。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'conversation'::public.material_category, ARRAY[E'salam', E'n5', E'starter']::text[], '[{"kanji":"はじめまして","kana":"はじめまして","meaning":"senang berkenalan"},{"kanji":"私","kana":"わたし","meaning":"saya"},{"kanji":"名前","kana":"なまえ","meaning":"nama"}]'::jsonb, '[{"pattern":"〜と申します","explanation":"Perkenalan formal: nama + と申します"}]'::jsonb, E'Membungkuk (ojigi) adalah bagian penting dari salam di Jepang.', E'Halo, nama saya Mike. Senang berkenalan. Salam formal: おはようございます (pagi), こんにちは (siang).', E'jlpt_academic'::public.learning_path),
  (E'n5-angka-waktu', E'Angka & Waktu — 数字と時間', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"一、二、三、四、五、六、七、八、九、十"}]},{"type":"paragraph","content":[{"type":"text","text":"今、何時ですか。三時です。"}]},{"type":"paragraph","content":[{"type":"text","text":"毎朝、七時に起きます。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'vocabulary'::public.material_category, ARRAY[E'angka', E'waktu', E'n5']::text[], '[{"kanji":"一","kana":"いち","meaning":"satu"},{"kanji":"二","kana":"に","meaning":"dua"},{"kanji":"時間","kana":"じかん","meaning":"waktu/jam"}]'::jsonb, '[{"pattern":"〜時〜分","explanation":"Menyebut waktu: 三時 = jam 3"}]'::jsonb, E'Jepang memakai dua sistem angka: kun-yomi (asli) dan on-yomi (Tionghoa).', E'Satu, dua, tiga... Jam berapa? Sekarang jam 3.', E'jlpt_academic'::public.learning_path),
  (E'n5-grammar-wa-ga', E'Partikel は dan が', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"私は学生です。"}]},{"type":"paragraph","content":[{"type":"text","text":"猫がいます。"}]},{"type":"paragraph","content":[{"type":"text","text":"田中さんは先生です。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'partikel', E'grammar', E'n5']::text[], '[{"kanji":"私","kana":"わたし","meaning":"saya"},{"kanji":"猫","kana":"ねこ","meaning":"kucing"}]'::jsonb, '[{"pattern":"AはBです","explanation":"Topik A, predikat B"},{"pattern":"Aがいます","explanation":"Ada A (benda hidup)"}]'::jsonb, E'Partikel は dibaca ''wa'' meski ditulis は (ha).', E'は menandai topik. が menandai subjek yang melakukan aksi.', E'jlpt_academic'::public.learning_path),
  (E'n5-grammar-wo-ni', E'Partikel を dan に', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"水を飲みます。"}]},{"type":"paragraph","content":[{"type":"text","text":"学校に行きます。"}]},{"type":"paragraph","content":[{"type":"text","text":"友達に会いました。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'partikel', E'grammar', E'n5']::text[], '[{"kanji":"水","kana":"みず","meaning":"air"},{"kanji":"学校","kana":"がっこう","meaning":"sekolah"}]'::jsonb, '[{"pattern":"NをV","explanation":"Objek langsung + kata kerja"},{"pattern":"Nに行く","explanation":"Pergi ke N"}]'::jsonb, E'を hampir selalu ditulis dengan hiragana を.', E'を untuk objek langsung. に untuk tujuan, waktu, dan lokasi.', E'jlpt_academic'::public.learning_path),
  (E'n5-grammar-masu', E'Kata Kerja ます形', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"毎日、ご飯を食べます。"}]},{"type":"paragraph","content":[{"type":"text","text":"お茶を飲みます。"}]},{"type":"paragraph","content":[{"type":"text","text":"日本語を勉強します。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'kata kerja', E'grammar', E'n5']::text[], '[{"kanji":"食べる","kana":"たべる","meaning":"makan"},{"kanji":"飲む","kana":"のむ","meaning":"minum"}]'::jsonb, '[{"pattern":"Vます","explanation":"Bentuk sopan kata kerja"}]'::jsonb, E'Bentuk ます adalah bentuk sopan standar dalam percakapan sehari-hari.', E'Bentuk ます untuk kata kerja sopan: makan → 食べます, minum → 飲みます.', E'jlpt_academic'::public.learning_path),
  (E'n5-adj-i', E'Kata Sifat い', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"この車は大きいです。"}]},{"type":"paragraph","content":[{"type":"text","text":"小さい犬がいます。"}]},{"type":"paragraph","content":[{"type":"text","text":"新しい本を買いました。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'kata sifat', E'grammar', E'n5']::text[], '[{"kanji":"大きい","kana":"おおきい","meaning":"besar"},{"kanji":"小さい","kana":"ちいさい","meaning":"kecil"}]'::jsonb, '[{"pattern":"いAdj + N","explanation":"Kata sifat い + kata benda"}]'::jsonb, E'Kata sifat い langsung memodifikasi kata benda tanpa partikel.', E'Kata sifat berakhiran い: 大きい (besar), 小さい (kecil), 新しい (baru).', E'jlpt_academic'::public.learning_path),
  (E'n5-adj-na', E'Kata Sifat な', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"この部屋は静かです。"}]},{"type":"paragraph","content":[{"type":"text","text":"元気な子供がいます。"}]},{"type":"paragraph","content":[{"type":"text","text":"きれいな花ですね。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'kata sifat', E'grammar', E'n5']::text[], '[{"kanji":"静か","kana":"しずか","meaning":"tenang"},{"kanji":"元気","kana":"げんき","meaning":"sehat/bersemangat"}]'::jsonb, '[{"pattern":"なAdj + な + N","explanation":"Perlu な sebelum kata benda"}]'::jsonb, E'Kata sifat な membutuhkan な sebelum kata benda.', E'Kata sifat な: きれい (cantik), 静か (tenang), 元気 (sehat).', E'jlpt_academic'::public.learning_path),
  (E'n5-negative', E'Bentuk Negatif', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"今日は学校に行きません。"}]},{"type":"paragraph","content":[{"type":"text","text":"肉を食べません。"}]},{"type":"paragraph","content":[{"type":"text","text":"お酒を飲みません。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'negatif', E'grammar', E'n5']::text[], '[{"kanji":"行く","kana":"いく","meaning":"pergi"},{"kanji":"食べる","kana":"たべる","meaning":"makan"}]'::jsonb, '[{"pattern":"Vません","explanation":"Bentuk negatif sopan"}]'::jsonb, E'Bentuk negatif sopan menggunakan ません.', E'Tidak makan → 食べません. Tidak pergi → 行きません.', E'jlpt_academic'::public.learning_path),
  (E'n5-past', E'Bentuk Lampau', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"昨日、映画を見ました。"}]},{"type":"paragraph","content":[{"type":"text","text":"朝ごはんを食べました。"}]},{"type":"paragraph","content":[{"type":"text","text":"友達と遊びました。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'masa lampau', E'grammar', E'n5']::text[], '[{"kanji":"昨日","kana":"きのう","meaning":"kemarin"},{"kanji":"見る","kana":"みる","meaning":"melihat"}]'::jsonb, '[{"pattern":"Vました","explanation":"Bentuk lampau sopan"}]'::jsonb, E'Bentuk lampau sopan: ました untuk afirmatif, ませんでした untuk negatif.', E'Sudah makan → 食べました. Kemarin pergi → 昨日行きました.', E'jlpt_academic'::public.learning_path),
  (E'n5-vocab-daily-1', E'Kosakata Harian 1', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"朝ごはんを食べて、コーヒーを飲みます。"}]},{"type":"paragraph","content":[{"type":"text","text":"夜、十時に寝ます。"}]},{"type":"paragraph","content":[{"type":"text","text":"毎日、学校に行きます。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'vocabulary'::public.material_category, ARRAY[E'kosakata', E'n5']::text[], '[{"kanji":"食べる","kana":"たべる","meaning":"makan"},{"kanji":"飲む","kana":"のむ","meaning":"minum"},{"kanji":"寝る","kana":"ねる","meaning":"tidur"}]'::jsonb, '[]'::jsonb, E'Kosakata sehari-hari adalah fondasi komunikasi dasar.', E'Kata sehari-hari: makan, minum, tidur, bangun, pergi.', E'jlpt_academic'::public.learning_path),
  (E'n5-vocab-daily-2', E'Kosakata Harian 2', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"毎日、新聞を読みます。"}]},{"type":"paragraph","content":[{"type":"text","text":"手紙を書きます。"}]},{"type":"paragraph","content":[{"type":"text","text":"音楽を聞きます。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'vocabulary'::public.material_category, ARRAY[E'kosakata', E'n5']::text[], '[{"kanji":"読む","kana":"よむ","meaning":"membaca"},{"kanji":"書く","kana":"かく","meaning":"menulis"},{"kanji":"聞く","kana":"きく","meaning":"mendengar"}]'::jsonb, '[]'::jsonb, E'Kata kerja dasar N5 sangat sering muncul di JLPT.', E'Membaca, menulis, mendengar, berbicara.', E'jlpt_academic'::public.learning_path),
  (E'n5-conversation-restaurant', E'Percakapan Restoran', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"店員：いらっしゃいませ。"}]},{"type":"paragraph","content":[{"type":"text","text":"客：ラーメンを一つください。"}]},{"type":"paragraph","content":[{"type":"text","text":"店員：かしこまりました。少々お待ちください。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'conversation'::public.material_category, ARRAY[E'percakapan', E'n5']::text[], '[{"kanji":"注文","kana":"ちゅうもん","meaning":"pesanan"},{"kanji":"会計","kana":"かいけい","meaning":"pembayaran"}]'::jsonb, '[{"pattern":"〜をください","explanation":"Tolong berikan..."}]'::jsonb, E'Di restoran Jepang, biasanya memanggil pelayan dengan すみません.', E'Selamat datang. Mau pesan apa? Saya mau ramen.', E'jlpt_academic'::public.learning_path),
  (E'n5-conversation-shopping', E'Percakapan Belanja', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"客：このシャツはいくらですか。"}]},{"type":"paragraph","content":[{"type":"text","text":"店員：三千円です。"}]},{"type":"paragraph","content":[{"type":"text","text":"客：じゃあ、これを買います。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'conversation'::public.material_category, ARRAY[E'percakapan', E'n5']::text[], '[{"kanji":"いくら","kana":"いくら","meaning":"berapa harga"},{"kanji":"買う","kana":"かう","meaning":"membeli"}]'::jsonb, '[{"pattern":"いくらですか","explanation":"Menanyakan harga"}]'::jsonb, E'Konbini (toko serba ada) sangat umum di Jepang.', E'Berapa harganya? Saya mau membeli ini.', E'jlpt_academic'::public.learning_path),
  (E'n5-grammar-review-1', E'Grammar N5 Review 1', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"私は毎日、日本語を勉強します。"}]},{"type":"paragraph","content":[{"type":"text","text":"猫が三匹います。"}]},{"type":"paragraph","content":[{"type":"text","text":"東京に行きたいです。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'review', E'n5']::text[], '[]'::jsonb, '[{"pattern":"は/が/を/に","explanation":"Review partikel dasar"}]'::jsonb, E'Review partikel dan bentuk dasar.', E'Review partikel は、が、を、に dan bentuk ます.', E'jlpt_academic'::public.learning_path),
  (E'n5-grammar-review-2', E'Grammar N5 Review 2', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"昨日は雨でした。今日は行きません。"}]},{"type":"paragraph","content":[{"type":"text","text":"先週、京都に行きました。"}]},{"type":"paragraph","content":[{"type":"text","text":"お酒を飲みませんでした。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'review', E'n5']::text[], '[]'::jsonb, '[{"pattern":"ません/ました","explanation":"Review negatif dan lampau"}]'::jsonb, E'Review bentuk negatif dan lampau.', E'Review ません dan ました.', E'jlpt_academic'::public.learning_path),
  (E'n5-reading-1', E'Reading N5 1 — 短い文章', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"私は毎朝、六時に起きます。"}]},{"type":"paragraph","content":[{"type":"text","text":"朝ごはんにパンと牛乳を食べます。"}]},{"type":"paragraph","content":[{"type":"text","text":"八時に学校に行きます。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'reading'::public.material_category, ARRAY[E'reading', E'n5']::text[], '[{"kanji":"毎朝","kana":"まいあさ","meaning":"setiap pagi"}]'::jsonb, '[]'::jsonb, E'Membaca teks pendek adalah keterampilan penting JLPT N5.', E'Saya bangun jam 6 setiap pagi. Sarapan roti dan susu. Berangkat sekolah jam 8.', E'jlpt_academic'::public.learning_path),
  (E'n5-reading-2', E'Reading N5 2 — 週末の予定', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"週末、友達と公園に行きます。"}]},{"type":"paragraph","content":[{"type":"text","text":"天気がいいです。"}]},{"type":"paragraph","content":[{"type":"text","text":"レストランで昼ごはんを食べます。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'reading'::public.material_category, ARRAY[E'reading', E'n5']::text[], '[{"kanji":"週末","kana":"しゅうまつ","meaning":"akhir pekan"}]'::jsonb, '[]'::jsonb, E'JLPT N5 reading sering tentang kegiatan sehari-hari.', E'Akhir pekan saya pergi ke taman dengan teman. Cuaca bagus. Kami makan lunch di restoran.', E'jlpt_academic'::public.learning_path),
  (E'n5-exam-prep', E'Persiapan Ujian N5', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"JLPT N5の試験は、語彙・文法・読解があります。"}]},{"type":"paragraph","content":[{"type":"text","text":"毎日、少しずつ勉強しましょう。"}]},{"type":"paragraph","content":[{"type":"text","text":"模擬試験を受けて、弱点を確認しましょう。"}]}]}'::jsonb, E'n5'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'ujian', E'n5']::text[], '[]'::jsonb, '[{"pattern":"試験対策","explanation":"Strategi persiapan ujian"}]'::jsonb, E'JLPT N5 passing score sekitar 80/180 poin (standar resmi).', E'Tips ujian: latih kosakata, partikel, dan membaca teks pendek.', E'jlpt_academic'::public.learning_path),
  (E'n4-te-form', E'Bentuk て形 — Te-form', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"朝ごはんを食べて、学校に行きます。"}]},{"type":"paragraph","content":[{"type":"text","text":"ここに座ってください。"}]},{"type":"paragraph","content":[{"type":"text","text":"本を読んで、寝ます。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'te-form', E'n4']::text[], '[{"kanji":"食べる","kana":"たべる","meaning":"makan"},{"kanji":"座る","kana":"すわる","meaning":"duduk"}]'::jsonb, '[{"pattern":"Vて、V","explanation":"Menghubungkan dua aksi"},{"pattern":"Vてください","explanation":"Permintaan sopan"}]'::jsonb, E'Te-form digunakan untuk menghubungkan kalimat dan meminta tolong.', E'Te-form: makan lalu minum → 食べて、飲みます. Tolong duduk → 座ってください.', E'jlpt_academic'::public.learning_path),
  (E'n4-potential', E'Bentuk Potensial — できる', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"日本語ができます。"}]},{"type":"paragraph","content":[{"type":"text","text":"泳げます。"}]},{"type":"paragraph","content":[{"type":"text","text":"この漢字が読めます。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'potensial', E'n4']::text[], '[{"kanji":"できる","kana":"できる","meaning":"bisa/mampu"},{"kanji":"泳ぐ","kana":"およぐ","meaning":"berenang"}]'::jsonb, '[{"pattern":"Nができる / Vられる","explanation":"Menyatakan kemampuan"}]'::jsonb, E'Bentuk potensial menyatakan kemampuan atau kemungkinan.', E'Bisa bahasa Jepang → 日本語ができます. Bisa makan → 食べられる.', E'jlpt_academic'::public.learning_path),
  (E'n4-comparison', E'Perbandingan — より/ほうが', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"京都より東京のほうがにぎやかです。"}]},{"type":"paragraph","content":[{"type":"text","text":"コーヒーのほうがお茶より好きです。"}]},{"type":"paragraph","content":[{"type":"text","text":"バスのほうがタクシーより安いです。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'perbandingan', E'n4']::text[], '[{"kanji":"より","kana":"より","meaning":"daripada"},{"kanji":"ほう","kana":"ほう","meaning":"arah/pihak"}]'::jsonb, '[{"pattern":"AよりBのほうが〜","explanation":"B lebih ~ daripada A"}]'::jsonb, E'より = daripada. ほうが = lebih (pilihan yang lebih baik).', E'Tokyo lebih ramai daripada Kyoto. Saya lebih suka kopi daripada teh.', E'jlpt_academic'::public.learning_path),
  (E'n4-tai-form', E'Keinginan — たい形', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"日本に行きたいです。"}]},{"type":"paragraph","content":[{"type":"text","text":"寿司を食べたいです。"}]},{"type":"paragraph","content":[{"type":"text","text":"新しい車を買いたいです。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'tai-form', E'n4']::text[], '[{"kanji":"行きたい","kana":"いきたい","meaning":"ingin pergi"},{"kanji":"食べたい","kana":"たべたい","meaning":"ingin makan"}]'::jsonb, '[{"pattern":"Vたい","explanation":"Ingin melakukan V"}]'::jsonb, E'たい形 menyatakan keinginan pribadi pembicara.', E'Ingin makan → 食べたい. Ingin pergi ke Jepang → 日本に行きたい.', E'jlpt_academic'::public.learning_path),
  (E'n4-naide', E'Bentuk ないで — Tanpa melakukan', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"朝ごはんを食べないで、学校に行きました。"}]},{"type":"paragraph","content":[{"type":"text","text":"ここでタバコを吸わないでください。"}]},{"type":"paragraph","content":[{"type":"text","text":"傘を持たないで、出かけました。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'naide', E'n4']::text[], '[{"kanji":"吸う","kana":"すう","meaning":"menghisap/merokok"}]'::jsonb, '[{"pattern":"Vないで","explanation":"Tanpa melakukan / jangan lakukan"}]'::jsonb, E'ないで bisa berarti ''tanpa melakukan'' atau permintaan negatif.', E'Tanpa makan → 食べないで. Jangan merokok → タバコを吸わないでください.', E'jlpt_academic'::public.learning_path),
  (E'n4-reading-email', E'Membaca Email Singkat', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"田中さん、お疲れ様です。"}]},{"type":"paragraph","content":[{"type":"text","text":"明日の会議は十時からです。"}]},{"type":"paragraph","content":[{"type":"text","text":"遅れないようにお願いします。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'reading'::public.material_category, ARRAY[E'reading', E'email', E'n4']::text[], '[{"kanji":"会議","kana":"かいぎ","meaning":"rapat"},{"kanji":"遅れる","kana":"おくれる","meaning":"terlambat"}]'::jsonb, '[]'::jsonb, E'Email formal di Jepang menggunakan bahasa sopan (keigo dasar).', E'Email: Besok rapat jam 10. Tolong datang tepat waktu.', E'jlpt_academic'::public.learning_path),
  (E'n4-vocab-daily-1', E'Kosakata N4 — Kehidupan Sehari-hari', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"荷物を届けます。"}]},{"type":"paragraph","content":[{"type":"text","text":"重い箱を運びます。"}]},{"type":"paragraph","content":[{"type":"text","text":"手紙が届きました。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'vocabulary'::public.material_category, ARRAY[E'kosakata', E'n4']::text[], '[{"kanji":"届ける","kana":"とどける","meaning":"mengirimkan/menyerahkan"},{"kanji":"運ぶ","kana":"はこぶ","meaning":"mengangkut"},{"kanji":"届く","kana":"とどく","meaning":"sampai (tiba)"}]'::jsonb, '[]'::jsonb, E'Kosakata N4 mencakup topik lebih luas dari N5.', E'Bekerja, istirahat, bepergian, mengirim.', E'jlpt_academic'::public.learning_path),
  (E'n4-vocab-daily-2', E'Kosakata N4 — Perasaan & Kondisi', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"試験に合格して、嬉しいです。"}]},{"type":"paragraph","content":[{"type":"text","text":"友達が帰って、悲しいです。"}]},{"type":"paragraph","content":[{"type":"text","text":"仕事が忙しくて、疲れました。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'vocabulary'::public.material_category, ARRAY[E'kosakata', E'n4']::text[], '[{"kanji":"嬉しい","kana":"うれしい","meaning":"senang"},{"kanji":"悲しい","kana":"かなしい","meaning":"sedih"},{"kanji":"疲れる","kana":"つかれる","meaning":"lelah"}]'::jsonb, '[]'::jsonb, E'Menyatakan perasaan adalah keterampilan penting N4.', E'Senang, sedih, lelah, khawatir.', E'jlpt_academic'::public.learning_path),
  (E'n4-grammar-ba', E'Bentuk ば — Kondisi', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"雨が降れば、傘を持って行きます。"}]},{"type":"paragraph","content":[{"type":"text","text":"安ければ、買います。"}]},{"type":"paragraph","content":[{"type":"text","text":"早く行けば、間に合います。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'grammar', E'ba', E'n4']::text[], '[{"kanji":"降る","kana":"ふる","meaning":"turun (hujan)"}]'::jsonb, '[{"pattern":"Vば","explanation":"Kondisi: jika..."}]'::jsonb, E'ば menyatakan kondisi ''jika''.', E'Jika hujan → 雨が降れば. Jika murah, saya beli.', E'jlpt_academic'::public.learning_path),
  (E'n4-grammar-tara', E'Bentuk たら — Setelah/Jika', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"ご飯を食べたら、出かけます。"}]},{"type":"paragraph","content":[{"type":"text","text":"仕事が終わったら、電話します。"}]},{"type":"paragraph","content":[{"type":"text","text":"日本に着いたら、連絡します。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'grammar', E'tara', E'n4']::text[], '[{"kanji":"終わる","kana":"おわる","meaning":"selesai"}]'::jsonb, '[{"pattern":"Vたら","explanation":"Setelah / jika sudah..."}]'::jsonb, E'たら bisa berarti ''setelah'' atau ''jika''.', E'Setelah makan → 食べたら. Jika sudah selesai → 終わったら.', E'jlpt_academic'::public.learning_path),
  (E'n4-conversation-phone', E'Percakapan Telepon', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"もしもし、田中です。"}]},{"type":"paragraph","content":[{"type":"text","text":"山田さんはいらっしゃいますか。"}]},{"type":"paragraph","content":[{"type":"text","text":"すみません、山田は今、留守です。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'conversation'::public.material_category, ARRAY[E'percakapan', E'n4']::text[], '[{"kanji":"電話","kana":"でんわ","meaning":"telepon"},{"kanji":"留守","kana":"るす","meaning":"tidak ada/tidak di tempat"}]'::jsonb, '[{"pattern":"〜ていらっしゃいますか","explanation":"Apakah ... ada?"}]'::jsonb, E'Saat menerima telepon: もしもし.', E'Halo, ini Tanaka. Bisa bicara dengan Yamada-san?', E'jlpt_academic'::public.learning_path),
  (E'n4-reading-short', E'Reading N4 — Teks Pendek', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"日本の夏は暑くて、湿度が高いです。"}]},{"type":"paragraph","content":[{"type":"text","text":"多くの人が海に行きます。"}]},{"type":"paragraph","content":[{"type":"text","text":"夏休みは八月からです。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'reading'::public.material_category, ARRAY[E'reading', E'n4']::text[], '[{"kanji":"夏","kana":"なつ","meaning":"musim panas"},{"kanji":"海","kana":"うみ","meaning":"laut"}]'::jsonb, '[]'::jsonb, E'N4 reading melibatkan paragraf 3-5 kalimat.', E'Musim panas di Jepang panas dan lembap. Banyak orang pergi ke pantai.', E'jlpt_academic'::public.learning_path),
  (E'n4-grammar-review-1', E'Grammar N4 Review 1', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"本を読んで、寝ました。"}]},{"type":"paragraph","content":[{"type":"text","text":"日本語が話せます。"}]},{"type":"paragraph","content":[{"type":"text","text":"この問題が解けますか。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'review', E'n4']::text[], '[]'::jsonb, '[{"pattern":"て形/可能形","explanation":"Review N4 grammar"}]'::jsonb, E'Review te-form dan potensial.', E'Review て形 dan られる.', E'jlpt_academic'::public.learning_path),
  (E'n4-grammar-review-2', E'Grammar N4 Review 2', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"電車のほうがバスより速いです。"}]},{"type":"paragraph","content":[{"type":"text","text":"旅行に行きたいです。"}]},{"type":"paragraph","content":[{"type":"text","text":"もっと日本語を勉強したいです。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'review', E'n4']::text[], '[]'::jsonb, '[{"pattern":"より/たい","explanation":"Review perbandingan dan keinginan"}]'::jsonb, E'Review perbandingan dan keinginan.', E'Review より/ほうが dan たい.', E'jlpt_academic'::public.learning_path),
  (E'n4-exam-prep', E'Persiapan Ujian N4', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"JLPT N4では、N5の知識も必要です。"}]},{"type":"paragraph","content":[{"type":"text","text":"て形、可能形、たい形を復習しましょう。"}]},{"type":"paragraph","content":[{"type":"text","text":"模擬試験で実力を確認しましょう。"}]}]}'::jsonb, E'n4'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'ujian', E'n4']::text[], '[]'::jsonb, '[{"pattern":"N4対策","explanation":"Strategi ujian N4"}]'::jsonb, E'JLPT N4 membutuhkan penguasaan N5 + grammar N4.', E'Latih te-form, potensial, dan reading paragraf pendek.', E'jlpt_academic'::public.learning_path),
  (E'jft-workplace-greeting', E'Salam di Tempat Kerja', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"おはようございます。新しい介護士の田中です。"}]},{"type":"paragraph","content":[{"type":"text","text":"今日からお世話になります。"}]},{"type":"paragraph","content":[{"type":"text","text":"よろしくお願いします。"}]}]}'::jsonb, E'none'::public.jlpt_level, E'conversation'::public.material_category, ARRAY[E'jft', E'tempat kerja']::text[], '[{"kanji":"おはようございます","kana":"おはようございます","meaning":"selamat pagi (formal)"},{"kanji":"介護士","kana":"かいごし","meaning":"caregiver"}]'::jsonb, '[]'::jsonb, E'Di fasilitas perawatan, salam pagi sangat penting untuk membangun kepercayaan.', E'Selamat pagi. Saya caregiver baru. Mohon bantuannya.', E'jft_practical'::public.learning_path),
  (E'jft-self-intro', E'Perkenalan Diri — JFT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"はじめまして。佐藤と申します。"}]},{"type":"paragraph","content":[{"type":"text","text":"インドネシアから来ました。"}]},{"type":"paragraph","content":[{"type":"text","text":"四月からここで働いています。"}]}]}'::jsonb, E'none'::public.jlpt_level, E'conversation'::public.material_category, ARRAY[E'jft', E'perkenalan']::text[], '[{"kanji":"インドネシア","kana":"インドネシア","meaning":"Indonesia"},{"kanji":"四月","kana":"しがつ","meaning":"April"}]'::jsonb, '[]'::jsonb, E'Perkenalan diri yang jelas membantu komunikasi dengan pasien dan rekan kerja.', E'Nama saya Sato. Saya dari Indonesia. Saya bekerja di sini sejak bulan April.', E'jft_practical'::public.learning_path),
  (E'jft-numbers-time', E'Angka & Jam Kerja — JFT', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"朝のシフトは七時から十五時までです。"}]},{"type":"paragraph","content":[{"type":"text","text":"夜勤は二十二時から七時までです。"}]},{"type":"paragraph","content":[{"type":"text","text":"申し送りは十五時に行います。"}]}]}'::jsonb, E'none'::public.jlpt_level, E'vocabulary'::public.material_category, ARRAY[E'jft', E'angka']::text[], '[{"kanji":"シフト","kana":"シフト","meaning":"shift/jadwal kerja"},{"kanji":"夜勤","kana":"やきん","meaning":"shift malam"}]'::jsonb, '[]'::jsonb, E'Shift kerja di fasilitas perawatan: pagi, siang, malam.', E'Shift pagi jam 7-15. Shift malam jam 22-7.', E'jft_practical'::public.learning_path),
  (E'jft-simple-instructions', E'Instruksi Sederhana', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"ここに座ってください。"}]},{"type":"paragraph","content":[{"type":"text","text":"口を開けてください。"}]},{"type":"paragraph","content":[{"type":"text","text":"少々お待ちください。"}]}]}'::jsonb, E'none'::public.jlpt_level, E'conversation'::public.material_category, ARRAY[E'jft', E'instruksi']::text[], '[{"kanji":"口","kana":"くち","meaning":"mulut"},{"kanji":"待つ","kana":"まつ","meaning":"menunggu"}]'::jsonb, '[{"pattern":"〜てください","explanation":"Instruksi sopan"}]'::jsonb, E'Instruksi harus jelas, pelan, dan sopan kepada lansia.', E'Tolong duduk di sini. Tolong buka mulut. Tolong tunggu sebentar.', E'jft_practical'::public.learning_path),
  (E'jft-polite-requests', E'Permintaan Sopan', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"起きていただけますか。"}]},{"type":"paragraph","content":[{"type":"text","text":"お手伝いしましょうか。"}]},{"type":"paragraph","content":[{"type":"text","text":"お水をお持ちしましょうか。"}]}]}'::jsonb, E'none'::public.jlpt_level, E'conversation'::public.material_category, ARRAY[E'jft', E'sopan']::text[], '[{"kanji":"起きる","kana":"おきる","meaning":"bangun"},{"kanji":"手伝う","kana":"てつだう","meaning":"membantu"}]'::jsonb, '[{"pattern":"〜ていただけますか","explanation":"Permintaan sangat sopan"}]'::jsonb, E'Bahasa sopan sangat penting dalam perawatan lansia.', E'Bisakah Anda bangun? Bisakah saya membantu Anda?', E'jft_practical'::public.learning_path),
  (E'jft-patient-conversation', E'Percakapan dengan Pasien', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"今日のご気分はいかがですか。"}]},{"type":"paragraph","content":[{"type":"text","text":"どこかお痛いところはありますか。"}]},{"type":"paragraph","content":[{"type":"text","text":"少しお楽しみください。すぐ行きます。"}]}]}'::jsonb, E'none'::public.jlpt_level, E'conversation'::public.material_category, ARRAY[E'jft', E'pasien']::text[], '[{"kanji":"具合","kana":"ぐあい","meaning":"kondisi/kesehatan"},{"kanji":"痛い","kana":"いたい","meaning":"sakit"}]'::jsonb, '[]'::jsonb, E'Dengarkan keluhan pasien dengan sabar dan empati.', E'Bagaimana perasaan Anda hari ini? Apakah ada yang sakit?', E'jft_practical'::public.learning_path),
  (E'jft-care-vocab-1', E'Kosakata Perawatan 1', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"介護の仕事は大切です。"}]},{"type":"paragraph","content":[{"type":"text","text":"患者さんの体調を確認します。"}]},{"type":"paragraph","content":[{"type":"text","text":"お薬の時間です。"}]}]}'::jsonb, E'none'::public.jlpt_level, E'vocabulary'::public.material_category, ARRAY[E'jft', E'perawatan']::text[], '[{"kanji":"介護","kana":"かいご","meaning":"perawatan"},{"kanji":"患者","kana":"かんじゃ","meaning":"pasien"},{"kanji":"服薬","kana":"ふくやく","meaning":"minum obat"}]'::jsonb, '[]'::jsonb, E'Kosakata dasar perawatan lansia di Jepang.', E'Perawatan, pasien, vital sign, obat, makan.', E'jft_practical'::public.learning_path),
  (E'jft-care-vocab-2', E'Kosakata Perawatan 2', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"入浴の介助をします。"}]},{"type":"paragraph","content":[{"type":"text","text":"排泄の記録をつけます。"}]},{"type":"paragraph","content":[{"type":"text","text":"申し送りの記録を書きます。"}]}]}'::jsonb, E'none'::public.jlpt_level, E'vocabulary'::public.material_category, ARRAY[E'jft', E'perawatan']::text[], '[{"kanji":"入浴","kana":"にゅうよく","meaning":"mandi"},{"kanji":"排泄","kana":"はいせつ","meaning":"buang air"},{"kanji":"記録","kana":"きろく","meaning":"catatan"}]'::jsonb, '[]'::jsonb, E'Istilah teknis perawatan sering muncul di ujian JFT.', E'Mandi, ganti popok, transfer, catatan.', E'jft_practical'::public.learning_path),
  (E'jft-emergency', E'Situasi Darurat', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"利用者さんが転倒しました！"}]},{"type":"paragraph","content":[{"type":"text","text":"すぐに看護師に連絡してください。"}]},{"type":"paragraph","content":[{"type":"text","text":"バイタルを測定して、記録してください。"}]}]}'::jsonb, E'none'::public.jlpt_level, E'conversation'::public.material_category, ARRAY[E'jft', E'darurat']::text[], '[{"kanji":"転倒","kana":"てんとう","meaning":"jatuh"},{"kanji":"救急","kana":"きゅうきゅう","meaning":"gawat darurat"}]'::jsonb, '[]'::jsonb, E'Dalam darurat, tetap tenang dan laporkan ke perawat.', E'Pasien jatuh! Panggil perawat! Ukur vital sign!', E'jft_practical'::public.learning_path),
  (E'jft-review', E'Review JFT A2', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"JFTの試験は、漢字・語彙・会話・場面問題があります。"}]},{"type":"paragraph","content":[{"type":"text","text":"介護の場面を想定して勉強しましょう。"}]},{"type":"paragraph","content":[{"type":"text","text":"模擬試験で練習しましょう。"}]}]}'::jsonb, E'none'::public.jlpt_level, E'grammar'::public.material_category, ARRAY[E'jft', E'review']::text[], '[]'::jsonb, '[{"pattern":"JFT対策","explanation":"Persiapan ujian JFT"}]'::jsonb, E'JFT Basic fokus pada bahasa praktis untuk caregiver.', E'Review kosakata perawatan, percakapan, dan situasi.', E'jft_practical'::public.learning_path)
ON CONFLICT (starter_key) DO UPDATE SET
  title = EXCLUDED.title,
  content = EXCLUDED.content,
  level = EXCLUDED.level,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  vocabulary = EXCLUDED.vocabulary,
  grammar_notes = EXCLUDED.grammar_notes,
  cultural_note = EXCLUDED.cultural_note,
  indonesian_translation = EXCLUDED.indonesian_translation,
  path = EXCLUDED.path;

INSERT INTO public.starter_vocab
  (starter_key, kanji, kana, meaning, jlpt_level, tags)
VALUES
  (E'v-n5-001', E'私', E'わたし', E'saya', E'n5'::public.jlpt_level, ARRAY[E'pronomina']::text[]),
  (E'v-n5-002', E'食べる', E'たべる', E'makan', E'n5'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n5-003', E'飲む', E'のむ', E'minum', E'n5'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n5-004', E'行く', E'いく', E'pergi', E'n5'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n5-005', E'来る', E'くる', E'datang', E'n5'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n5-006', E'見る', E'みる', E'melihat', E'n5'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n5-007', E'聞く', E'きく', E'mendengar', E'n5'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n5-008', E'読む', E'よむ', E'membaca', E'n5'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n5-009', E'書く', E'かく', E'menulis', E'n5'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n5-010', E'話す', E'はなす', E'berbicara', E'n5'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n5-011', E'買う', E'かう', E'membeli', E'n5'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n5-012', E'売る', E'うる', E'menjual', E'n5'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n5-013', E'大きい', E'おおきい', E'besar', E'n5'::public.jlpt_level, ARRAY[E'kata sifat']::text[]),
  (E'v-n5-014', E'小さい', E'ちいさい', E'kecil', E'n5'::public.jlpt_level, ARRAY[E'kata sifat']::text[]),
  (E'v-n5-015', E'新しい', E'あたらしい', E'baru', E'n5'::public.jlpt_level, ARRAY[E'kata sifat']::text[]),
  (E'v-n5-016', E'古い', E'ふるい', E'lama/tua', E'n5'::public.jlpt_level, ARRAY[E'kata sifat']::text[]),
  (E'v-n5-017', E'高い', E'たかい', E'tinggi/mahal', E'n5'::public.jlpt_level, ARRAY[E'kata sifat']::text[]),
  (E'v-n5-018', E'安い', E'やすい', E'murah', E'n5'::public.jlpt_level, ARRAY[E'kata sifat']::text[]),
  (E'v-n5-019', E'学校', E'がっこう', E'sekolah', E'n5'::public.jlpt_level, ARRAY[E'tempat']::text[]),
  (E'v-n5-020', E'病院', E'びょういん', E'rumah sakit', E'n5'::public.jlpt_level, ARRAY[E'tempat']::text[]),
  (E'v-n5-021', E'駅', E'えき', E'stasiun', E'n5'::public.jlpt_level, ARRAY[E'tempat']::text[]),
  (E'v-n5-022', E'電車', E'でんしゃ', E'kereta', E'n5'::public.jlpt_level, ARRAY[E'transportasi']::text[]),
  (E'v-n5-023', E'友達', E'ともだち', E'teman', E'n5'::public.jlpt_level, ARRAY[E'orang']::text[]),
  (E'v-n5-024', E'先生', E'せんせい', E'guru', E'n5'::public.jlpt_level, ARRAY[E'orang']::text[]),
  (E'v-n5-025', E'学生', E'がくせい', E'pelajar', E'n5'::public.jlpt_level, ARRAY[E'orang']::text[]),
  (E'v-n5-026', E'天気', E'てんき', E'cuaca', E'n5'::public.jlpt_level, ARRAY[E'alam']::text[]),
  (E'v-n5-027', E'雨', E'あめ', E'hujan', E'n5'::public.jlpt_level, ARRAY[E'alam']::text[]),
  (E'v-n5-028', E'猫', E'ねこ', E'kucing', E'n5'::public.jlpt_level, ARRAY[E'hewan']::text[]),
  (E'v-n5-029', E'犬', E'いぬ', E'anjing', E'n5'::public.jlpt_level, ARRAY[E'hewan']::text[]),
  (E'v-n5-030', E'魚', E'さかな', E'ikan', E'n5'::public.jlpt_level, ARRAY[E'makanan']::text[]),
  (E'v-n5-031', E'肉', E'にく', E'daging', E'n5'::public.jlpt_level, ARRAY[E'makanan']::text[]),
  (E'v-n5-032', E'水', E'みず', E'air', E'n5'::public.jlpt_level, ARRAY[E'makanan']::text[]),
  (E'v-n5-033', E'朝', E'あさ', E'pagi', E'n5'::public.jlpt_level, ARRAY[E'waktu']::text[]),
  (E'v-n5-034', E'夜', E'よる', E'malam', E'n5'::public.jlpt_level, ARRAY[E'waktu']::text[]),
  (E'v-n5-035', E'今日', E'きょう', E'hari ini', E'n5'::public.jlpt_level, ARRAY[E'waktu']::text[]),
  (E'v-n5-036', E'明日', E'あした', E'besok', E'n5'::public.jlpt_level, ARRAY[E'waktu']::text[]),
  (E'v-n5-037', E'昨日', E'きのう', E'kemarin', E'n5'::public.jlpt_level, ARRAY[E'waktu']::text[]),
  (E'v-n5-038', E'一', E'いち', E'satu', E'n5'::public.jlpt_level, ARRAY[E'angka']::text[]),
  (E'v-n5-039', E'二', E'に', E'dua', E'n5'::public.jlpt_level, ARRAY[E'angka']::text[]),
  (E'v-n5-040', E'三', E'さん', E'tiga', E'n5'::public.jlpt_level, ARRAY[E'angka']::text[]),
  (E'v-n4-001', E'届ける', E'とどける', E'mengirimkan', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-002', E'運ぶ', E'はこぶ', E'mengangkut', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-003', E'届く', E'とどく', E'sampai/tiba', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-004', E'嬉しい', E'うれしい', E'senang', E'n4'::public.jlpt_level, ARRAY[E'kata sifat']::text[]),
  (E'v-n4-005', E'悲しい', E'かなしい', E'sedih', E'n4'::public.jlpt_level, ARRAY[E'kata sifat']::text[]),
  (E'v-n4-006', E'疲れる', E'つかれる', E'lelah', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-007', E'会議', E'かいぎ', E'rapat', E'n4'::public.jlpt_level, ARRAY[E'noun']::text[]),
  (E'v-n4-008', E'遅れる', E'おくれる', E'terlambat', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-009', E'終わる', E'おわる', E'selesai', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-010', E'降る', E'ふる', E'turun (hujan)', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-011', E'泳ぐ', E'およぐ', E'berenang', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-012', E'留守', E'るす', E'tidak di tempat', E'n4'::public.jlpt_level, ARRAY[E'noun']::text[]),
  (E'v-n4-013', E'連絡', E'れんらく', E'kontak/hubungi', E'n4'::public.jlpt_level, ARRAY[E'noun']::text[]),
  (E'v-n4-014', E'準備', E'じゅんび', E'persiapan', E'n4'::public.jlpt_level, ARRAY[E'noun']::text[]),
  (E'v-n4-015', E'説明', E'せつめい', E'penjelasan', E'n4'::public.jlpt_level, ARRAY[E'noun']::text[]),
  (E'v-n4-016', E'経験', E'けいけん', E'pengalaman', E'n4'::public.jlpt_level, ARRAY[E'noun']::text[]),
  (E'v-n4-017', E'趣味', E'しゅみ', E'hobi', E'n4'::public.jlpt_level, ARRAY[E'noun']::text[]),
  (E'v-n4-018', E'予定', E'よてい', E'rencana', E'n4'::public.jlpt_level, ARRAY[E'noun']::text[]),
  (E'v-n4-019', E'約束', E'やくそく', E'janji', E'n4'::public.jlpt_level, ARRAY[E'noun']::text[]),
  (E'v-n4-020', E'心配', E'しんぱい', E'khawatir', E'n4'::public.jlpt_level, ARRAY[E'noun']::text[]),
  (E'v-n4-021', E'複雑', E'ふくざつ', E'rumit', E'n4'::public.jlpt_level, ARRAY[E'kata sifat']::text[]),
  (E'v-n4-022', E'簡単', E'かんたん', E'mudah', E'n4'::public.jlpt_level, ARRAY[E'kata sifat']::text[]),
  (E'v-n4-023', E'必要', E'ひつよう', E'perlu', E'n4'::public.jlpt_level, ARRAY[E'kata sifat']::text[]),
  (E'v-n4-024', E'大切', E'たいせつ', E'penting', E'n4'::public.jlpt_level, ARRAY[E'kata sifat']::text[]),
  (E'v-n4-025', E'調べる', E'しらべる', E'menyelidiki', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-026', E'集める', E'あつめる', E'mengumpulkan', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-027', E'続ける', E'つづける', E'melanjutkan', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-028', E'変える', E'かえる', E'mengubah', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-029', E'決める', E'きめる', E'memutuskan', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-n4-030', E'間に合う', E'まにあう', E'tepat waktu', E'n4'::public.jlpt_level, ARRAY[E'kata kerja']::text[]),
  (E'v-jft-001', E'介護', E'かいご', E'perawatan', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-002', E'患者', E'かんじゃ', E'pasien', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-003', E'利用者', E'りようしゃ', E'pengguna layanan', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-004', E'介護士', E'かいごし', E'caregiver', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-005', E'看護師', E'かんごし', E'perawat', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-006', E'服薬', E'ふくやく', E'minum obat', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-007', E'入浴', E'にゅうよく', E'mandi', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-008', E'排泄', E'はいせつ', E'buang air', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-009', E'清拭', E'せいしき', E'membersihkan tubuh', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-010', E'移乗', E'いじょう', E'transfer pasien', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-011', E'車椅子', E'くるまいす', E'kursi roda', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-012', E'体温', E'たいおん', E'suhu tubuh', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-013', E'血圧', E'けつあつ', E'tekanan darah', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-014', E'症状', E'しょうじょう', E'gejala', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-015', E'記録', E'きろく', E'catatan', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-016', E'申し送り', E'もうしおくり', E'serah terima shift', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-017', E'転倒', E'てんとう', E'jatuh', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-018', E'誤嚥', E'ごえん', E'salah menelan', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-019', E'褥瘡', E'じょくそう', E'luka tekan', E'none'::public.jlpt_level, ARRAY[E'jft']::text[]),
  (E'v-jft-020', E'バイタル', E'バイタル', E'tanda vital', E'none'::public.jlpt_level, ARRAY[E'jft']::text[])
ON CONFLICT (starter_key) DO UPDATE SET
  kanji = EXCLUDED.kanji,
  kana = EXCLUDED.kana,
  meaning = EXCLUDED.meaning,
  jlpt_level = EXCLUDED.jlpt_level,
  tags = EXCLUDED.tags;

-- Provision function
CREATE OR REPLACE FUNCTION public.provision_starter_content(p_user_id uuid, p_path public.learning_path DEFAULT 'jlpt_academic')
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_mat record;
  v_vocab record;
  v_new_mat_id uuid;
  v_new_vocab_id uuid;
BEGIN
  IF EXISTS (SELECT 1 FROM public.materials WHERE user_id = p_user_id LIMIT 1) THEN
    RETURN;
  END IF;

  FOR v_mat IN
    SELECT * FROM public.starter_materials
    ORDER BY starter_key
  LOOP
    INSERT INTO public.materials (
      user_id, title, content, level, category, tags,
      vocabulary, grammar_notes, cultural_note, indonesian_translation, starter_key
    ) VALUES (
      p_user_id, v_mat.title, v_mat.content, v_mat.level, v_mat.category, v_mat.tags,
      v_mat.vocabulary, v_mat.grammar_notes, v_mat.cultural_note, v_mat.indonesian_translation, v_mat.starter_key
    )
    RETURNING id INTO v_new_mat_id;
  END LOOP;

  FOR v_vocab IN
    SELECT * FROM public.starter_vocab
    ORDER BY starter_key
  LOOP
    INSERT INTO public.vocab_bank (user_id, kanji, kana, meaning, jlpt_level, tags)
    VALUES (p_user_id, v_vocab.kanji, v_vocab.kana, v_vocab.meaning, v_vocab.jlpt_level, v_vocab.tags)
    RETURNING id INTO v_new_vocab_id;

    INSERT INTO public.srs_logs (user_id, vocab_id, status, repetitions, ease_factor, interval_days, next_review_date)
    VALUES (p_user_id, v_new_vocab_id, 'new', 0, 2.5, 0, now());
  END LOOP;
END;
$$;

-- Update signup trigger
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'display_name', NEW.email));
  PERFORM public.provision_starter_content(NEW.id, 'jlpt_academic');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Backfill existing users without materials
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT id, current_path FROM public.profiles p
    WHERE NOT EXISTS (SELECT 1 FROM public.materials m WHERE m.user_id = p.id)
  LOOP
    PERFORM public.provision_starter_content(r.id, r.current_path);
  END LOOP;
END $$;
