-- Seed exam questions: 60 JLPT N5 + 40 JFT Basic
-- Generated from placeholder data in useExamQuestions.ts and useJftQuestions.ts

INSERT INTO public.exam_questions
  (question_text, options, correct_answer, exam_type, level, section, difficulty, explanation, is_active, transcript, image_prompt)
VALUES
  (E'「食べる」の読み方は？', '["たべる","のべる","くべる","しべる"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「食べる」dibaca たべる (taberu).', true, NULL, NULL),
  (E'「大きい」の意味は？', '["Small","Big","Fast","Slow"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「大きい」(ookii) berarti besar.', true, NULL, NULL),
  (E'「学校」の読み方は？', '["がくこう","がっこう","がくこ","がっこ"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「学校」dibaca がっこう (gakkou).', true, NULL, NULL),
  (E'「飲む」の意味は？', '["To eat","To sleep","To drink","To walk"]'::jsonb, 2, 'jlpt', 'n5', 'vocabulary', 3, E'「飲む」(nomu) berarti minum.', true, NULL, NULL),
  (E'「天気」の読み方は？', '["てんき","でんき","てんぎ","でんぎ"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「天気」dibaca てんき (tenki).', true, NULL, NULL),
  (E'「友達」の意味は？', '["Teacher","Student","Friend","Parent"]'::jsonb, 2, 'jlpt', 'n5', 'vocabulary', 3, E'「友達」(tomodachi) berarti teman.', true, NULL, NULL),
  (E'「書く」の読み方は？', '["かく","きく","けく","こく"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「書く」dibaca かく (kaku).', true, NULL, NULL),
  (E'「電車」の意味は？', '["Bus","Car","Bicycle","Train"]'::jsonb, 3, 'jlpt', 'n5', 'vocabulary', 3, E'「電車」(densha) berarti kereta.', true, NULL, NULL),
  (E'「朝」の読み方は？', '["よる","あさ","ひる","ゆう"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「朝」dibaca あさ (asa).', true, NULL, NULL),
  (E'「高い」の意味は？', '["Low","Cheap","Expensive/Tall","Short"]'::jsonb, 2, 'jlpt', 'n5', 'vocabulary', 3, E'「高い」(takai) berarti mahal/tinggi.', true, NULL, NULL),
  (E'「走る」の読み方は？', '["あるく","はしる","およぐ","とぶ"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「走る」dibaca はしる (hashiru).', true, NULL, NULL),
  (E'「病院」の意味は？', '["School","Hospital","Station","Library"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「病院」(byouin) berarti rumah sakit.', true, NULL, NULL),
  (E'「新しい」の読み方は？', '["あたらしい","ふるい","むずかしい","やさしい"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「新しい」dibaca あたらしい (atarashii).', true, NULL, NULL),
  (E'「仕事」の意味は？', '["Hobby","Work/Job","Study","Rest"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「仕事」(shigoto) berarti pekerjaan.', true, NULL, NULL),
  (E'「映画」の読み方は？', '["えが","えいが","えいか","えか"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「映画」dibaca えいが (eiga).', true, NULL, NULL),
  (E'「買う」の意味は？', '["To sell","To buy","To give","To receive"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「買う」(kau) berarti membeli.', true, NULL, NULL),
  (E'「入る」の読み方は？', '["はいる","でる","いる","おる"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「入る」dibaca はいる (hairu).', true, NULL, NULL),
  (E'「魚」の意味は？', '["Meat","Vegetable","Fruit","Fish"]'::jsonb, 3, 'jlpt', 'n5', 'vocabulary', 3, E'「魚」(sakana) berarti ikan.', true, NULL, NULL),
  (E'「寒い」の読み方は？', '["あつい","さむい","すずしい","あたたかい"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「寒い」dibaca さむい (samui).', true, NULL, NULL),
  (E'「窓」の意味は？', '["Door","Wall","Window","Floor"]'::jsonb, 2, 'jlpt', 'n5', 'vocabulary', 3, E'「窓」(mado) berarti jendela.', true, NULL, NULL),
  (E'私＿学生です。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'Partikel は menandai topik kalimat.', true, NULL, NULL),
  (E'東京＿行きます。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Partikel に menandai tujuan pergerakan.', true, NULL, NULL),
  (E'水＿飲みます。', '["は","が","を","に"]'::jsonb, 2, 'jlpt', 'n5', 'grammar', 3, E'Partikel を menandai objek langsung.', true, NULL, NULL),
  (E'昨日、映画＿見ました。', '["は","が","を","に"]'::jsonb, 2, 'jlpt', 'n5', 'grammar', 3, E'Objek dari 見る adalah を.', true, NULL, NULL),
  (E'友達＿会いました。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'会う membutuhkan partikel に.', true, NULL, NULL),
  (E'ここ＿座ってください。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'座る di lokasi memakai に.', true, NULL, NULL),
  (E'日本語＿勉強します。', '["は","が","を","に"]'::jsonb, 2, 'jlpt', 'n5', 'grammar', 3, E'勉強する memakai を untuk objek.', true, NULL, NULL),
  (E'バス＿乗ります。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'乗る memakai に untuk alat transportasi.', true, NULL, NULL),
  (E'この本＿面白いです。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'Topik kalimat menggunakan は.', true, NULL, NULL),
  (E'猫＿います。', '["は","が","を","に"]'::jsonb, 1, 'jlpt', 'n5', 'grammar', 3, E'Keberadaan benda hidup memakai が.', true, NULL, NULL),
  (E'明日、学校＿行きません。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Tujuan pergerakan memakai に.', true, NULL, NULL),
  (E'コーヒー＿好きです。', '["は","が","を","に"]'::jsonb, 1, 'jlpt', 'n5', 'grammar', 3, E'好き memakai が untuk objek kesukaan.', true, NULL, NULL),
  (E'どこ＿行きますか。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Tujuan pertanyaan pergerakan memakai に.', true, NULL, NULL),
  (E'毎朝、六時＿起きます。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Waktu spesifik memakai に.', true, NULL, NULL),
  (E'これ＿何ですか。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'これ sebagai topik memakai は.', true, NULL, NULL),
  (E'田中さん＿先生です。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'Identitas topik memakai は.', true, NULL, NULL),
  (E'公園＿散歩します。', '["は","が","を","で"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Lokasi aktivitas memakai で.', true, NULL, NULL),
  (E'電車＿来ました。', '["は","が","を","に"]'::jsonb, 1, 'jlpt', 'n5', 'grammar', 3, E'Subjek aksi datang memakai が.', true, NULL, NULL),
  (E'夏＿暑いです。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'Musim sebagai topik memakai は.', true, NULL, NULL),
  (E'母＿料理を作ります。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'Pelaku sebagai topik memakai は.', true, NULL, NULL),
  (E'「私は毎日学校に行きます。」— 私はどこに行きますか？', '["家","学校","会社","公園"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'学校 = sekolah.', true, NULL, NULL),
  (E'「田中さんは先生です。」— 田中さんの仕事は何ですか？', '["医者","先生","学生","会社員"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'先生 = guru.', true, NULL, NULL),
  (E'「今日は天気がいいです。」— 天気はどうですか？', '["悪い","いい","寒い","暑い"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'天気がいい = cuaca bagus.', true, NULL, NULL),
  (E'「猫が三匹います。」— 猫は何匹いますか？', '["一匹","二匹","三匹","四匹"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'三匹 = tiga ekor.', true, NULL, NULL),
  (E'「日曜日に映画を見ます。」— いつ映画を見ますか？', '["月曜日","水曜日","金曜日","日曜日"]'::jsonb, 3, 'jlpt', 'n5', 'reading', 3, E'日曜日 = hari Minggu.', true, NULL, NULL),
  (E'「この本は面白いです。」— 本はどうですか？', '["つまらない","難しい","面白い","簡単"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'面白い = menarik.', true, NULL, NULL),
  (E'「朝ごはんにパンを食べました。」— 何を食べましたか？', '["ご飯","パン","麺","お菓子"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'パン = roti.', true, NULL, NULL),
  (E'「駅まで歩いて10分です。」— 駅まで何分ですか？', '["5分","10分","15分","20分"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'10分 = sepuluh menit.', true, NULL, NULL),
  (E'「母は料理が上手です。」— 母は何が上手ですか？', '["掃除","料理","運動","歌"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'料理が上手 = pandai memasak.', true, NULL, NULL),
  (E'「来週、大阪に行きます。」— いつ行きますか？', '["今週","来週","先週","毎週"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'来週 = minggu depan.', true, NULL, NULL),
  (E'「弟は5歳です。」— 弟は何歳ですか？', '["3歳","4歳","5歳","6歳"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'5歳 = lima tahun.', true, NULL, NULL),
  (E'「図書館で本を借りました。」— どこで借りましたか？', '["本屋","学校","図書館","家"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'図書館 = perpustakaan.', true, NULL, NULL),
  (E'「夏休みに海に行きたいです。」— どこに行きたいですか？', '["山","海","川","湖"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'海 = laut.', true, NULL, NULL),
  (E'「この花は赤いです。」— 花は何色ですか？', '["白","青","赤","黄色"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'赤い = merah.', true, NULL, NULL),
  (E'「兄は大学生です。」— 兄は何をしていますか？', '["仕事","大学","高校","中学"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'大学生 = mahasiswa.', true, NULL, NULL),
  (E'「昨日、友達と遊びました。」— 誰と遊びましたか？', '["家族","先生","友達","一人"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'友達 = teman.', true, NULL, NULL),
  (E'「冬は寒いです。」— 冬はどうですか？', '["暑い","涼しい","暖かい","寒い"]'::jsonb, 3, 'jlpt', 'n5', 'reading', 3, E'寒い = dingin.', true, NULL, NULL),
  (E'「毎晩、9時に寝ます。」— 何時に寝ますか？', '["8時","9時","10時","11時"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'9時 = jam 9.', true, NULL, NULL),
  (E'「父は会社で働いています。」— 父はどこで働いていますか？', '["学校","病院","会社","店"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'会社 = perusahaan.', true, NULL, NULL),
  (E'「このケーキはおいしいです。」— ケーキはどうですか？', '["まずい","おいしい","甘くない","辛い"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'おいしい = enak.', true, NULL, NULL),
  (E'「介護」の読み方は？', '["かいご","かいこ","けいご","けいこ"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「介護」dibaca かいご (kaigo).', true, NULL, NULL),
  (E'「患者」の読み方は？', '["かんしゃ","かんじゃ","がんしゃ","がんじゃ"]'::jsonb, 1, 'jft', 'jft', 'kanji_reading', 3, E'「患者」dibaca かんじゃ (kanja).', true, NULL, NULL),
  (E'「食事」の読み方は？', '["しょくじ","しょくし","しゅくじ","しゅくし"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「食事」dibaca しょくじ (shokuji).', true, NULL, NULL),
  (E'「体温」の読み方は？', '["たいおん","ていおん","たいうん","ていうん"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「体温」dibaca たいおん (taion).', true, NULL, NULL),
  (E'「血圧」の読み方は？', '["けつあつ","ちあつ","けちあつ","ちけつ"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「血圧」dibaca けつあつ (ketsuatsu).', true, NULL, NULL),
  (E'「入浴」の読み方は？', '["にゅうよく","いりよく","にゅうあび","いりあび"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「入浴」dibaca にゅうよく (nyuuyoku).', true, NULL, NULL),
  (E'「排泄」の読み方は？', '["はいせつ","はいさつ","ばいせつ","ばいさつ"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「排泄」dibaca はいせつ (haisetsu).', true, NULL, NULL),
  (E'「服薬」の読み方は？', '["ふくやく","ふくぐすり","はくやく","はくぐすり"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「服薬」dibaca ふくやく (fukuyaku).', true, NULL, NULL),
  (E'「記録」の読み方は？', '["きろく","ぎろく","きりょく","ぎりょく"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「記録」dibaca きろく (kiroku).', true, NULL, NULL),
  (E'「症状」の読み方は？', '["しょうじょう","せいじょう","しょうそう","せいそう"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「症状」dibaca しょうじょう (shoujou).', true, NULL, NULL),
  (E'「バイタル」とは何ですか？', '["生命徴候","薬の名前","食事の種類","運動の方法"]'::jsonb, 0, 'jft', 'jft', 'vocabulary', 3, E'バイタル = tanda-tanda vital.', true, NULL, NULL),
  (E'「おむつ交換」の意味は？', '["シーツを替える","おむつを替える","服を替える","靴を替える"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'おむつ交換 = ganti popok.', true, NULL, NULL),
  (E'「車椅子」の読み方は？', '["くるまいす","しゃいす","くるまかご","しゃかご"]'::jsonb, 0, 'jft', 'jft', 'vocabulary', 3, E'「車椅子」dibaca くるまいす (kurumaisu).', true, NULL, NULL),
  (E'「寝返り」の意味は？', '["起きること","寝ること","体の向きを変えること","歩くこと"]'::jsonb, 2, 'jft', 'jft', 'vocabulary', 3, E'寝返り = membalik badan.', true, NULL, NULL),
  (E'「誤嚥」の意味は？', '["食べ過ぎ","飲み込み間違い","アレルギー反応","消化不良"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'誤嚥 = salah menelan.', true, NULL, NULL),
  (E'「褥瘡」とは？', '["骨折","床ずれ","やけど","切り傷"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'褥瘡 = luka tekan (bedsore).', true, NULL, NULL),
  (E'「利用者」の意味は？', '["スタッフ","ケアを受ける人","医者","看護師"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'利用者 = pengguna layanan/pasien.', true, NULL, NULL),
  (E'「申し送り」の意味は？', '["手紙を送る","引き継ぎ報告","買い物リスト","休憩時間"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'申し送り = serah terima/shift report.', true, NULL, NULL),
  (E'「清拭」の意味は？', '["掃除すること","体を拭くこと","洗濯すること","料理すること"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'清拭 = membersihkan tubuh.', true, NULL, NULL),
  (E'「移乗」の意味は？', '["電車に乗る","ベッドから車椅子へ移ること","引っ越し","旅行"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'移乗 = transfer (bed ke kursi roda).', true, NULL, NULL),
  (E'🔊 「すみません、お水をもらえますか。」\n— 利用者さんは何を求めていますか？', '["食事","水","薬","トイレ"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'利用者 meminta air.', true, E'利用者：すみません、お水をもらえますか。\n介護士：はい、少々お待ちください。', NULL),
  (E'🔊 「今日は調子がいいです。」\n— 利用者さんの体調は？', '["悪い","普通","良い","わからない"]'::jsonb, 2, 'jft', 'jft', 'conversation', 3, E'Kondisi pasien baik hari ini.', true, E'介護士：今日のご気分はいかがですか？\n利用者：今日は調子がいいです。', NULL),
  (E'🔊 「少し寒いです。」\n— 何をすべきですか？', '["窓を開ける","エアコンを下げる","毛布をかける","水を持っていく"]'::jsonb, 2, 'jft', 'jft', 'conversation', 3, E'Pasien merasa dingin, beri selimut.', true, E'利用者：少し寒いです。\n介護士：毛布をお持ちしますね。', NULL),
  (E'🔊 「頭が痛いです。」\n— 利用者さんの症状は？', '["腹痛","頭痛","腰痛","歯痛"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Gejala: sakit kepala.', true, E'利用者：頭が痛いです。\n介護士：看護師に伝えますね。', NULL),
  (E'🔊 「トイレに行きたいです。」\n— 利用者さんは何をしたいですか？', '["食事","散歩","トイレ","入浴"]'::jsonb, 2, 'jft', 'jft', 'conversation', 3, E'Pasien ingin ke toilet.', true, E'利用者：トイレに行きたいです。\n介護士：お手伝いしますね。', NULL),
  (E'🔊 「お薬の時間ですよ。」\n— 介護士は何をしていますか？', '["食事の準備","服薬の案内","入浴の準備","体操の案内"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Pengingat waktu minum obat.', true, E'介護士：○○さん、お薬の時間ですよ。\n利用者：ありがとうございます。', NULL),
  (E'🔊 「腰が痛いので、ゆっくりお願いします。」\n— 何に注意すべきですか？', '["速く動く","ゆっくり動く","動かない","走る"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Gerakkan pasien perlahan.', true, E'利用者：腰が痛いので、ゆっくりお願いします。\n介護士：はい、ゆっくりしましょうね。', NULL),
  (E'🔊 「ご飯はもういらないです。」\n— 利用者さんは？', '["もっと食べたい","食事を終えたい","飲み物が欲しい","デザートが欲しい"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Pasien sudah selesai makan.', true, E'介護士：もう少し食べますか？\n利用者：ご飯はもういらないです。', NULL),
  (E'🔊 「散歩に行きましょうか。」\n— 介護士は何を提案していますか？', '["食事","入浴","散歩","睡眠"]'::jsonb, 2, 'jft', 'jft', 'conversation', 3, E'Caregiver mengajak jalan-jalan.', true, E'介護士：天気がいいですね。散歩に行きましょうか。\n利用者：はい、行きたいです。', NULL),
  (E'🔊 「夜、よく眠れましたか。」\n— 介護士は何を聞いていますか？', '["食事","睡眠","排泄","体温"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Menanyakan kualitas tidur malam.', true, E'介護士：おはようございます。夜、よく眠れましたか？\n利用者：はい、ぐっすり眠れました。', NULL),
  (E'📋 場面：利用者さんが転倒しました。\n最初に何をしますか？', '["すぐに起こす","安全を確認して声をかける","他の利用者に伝える","記録を書く"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Prioritas: pastikan keamanan pasien.', true, NULL, E'利用者が廊下で転倒した場面'),
  (E'📋 場面：利用者さんが「帰りたい」と言っています。\nどう対応しますか？', '["「帰れません」と言う","無視する","気持ちを聞いて寄り添う","家族に電話する"]'::jsonb, 2, 'jft', 'jft', 'situational', 3, E'Dengarkan dan dampingi perasaan pasien.', true, NULL, E'認知症の利用者が帰宅願望を示す場面'),
  (E'📋 場面：食事中に利用者さんがむせました。\nどうしますか？', '["水を飲ませる","食事を続ける","背中をさすって様子を見る","すぐに救急車を呼ぶ"]'::jsonb, 2, 'jft', 'jft', 'situational', 3, E'Tepuk punggung dan pantau kondisi.', true, NULL, E'食事介助中にむせた場面'),
  (E'📋 場面：利用者さんの顔色が悪いです。\n何をしますか？', '["そのまま様子を見る","バイタルを測定し報告する","食事を提供する","散歩に連れ出す"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Ukur vital sign dan laporkan.', true, NULL, E'利用者の体調変化に気づいた場面'),
  (E'📋 場面：他の介護士が休憩中です。ナースコールが鳴りました。\nどうしますか？', '["休憩中の人を呼ぶ","無視する","自分が対応する","後で対応する"]'::jsonb, 2, 'jft', 'jft', 'situational', 3, E'Tanggapi panggilan segera.', true, NULL, E'人手不足時のナースコール対応'),
  (E'📋 場面：入浴中に利用者さんが「熱い」と言いました。\nどうしますか？', '["我慢してもらう","すぐに温度を下げる","入浴を中止する","水を追加する"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Turunkan suhu air mandi.', true, NULL, E'入浴介助中の温度調整'),
  (E'📋 場面：利用者さんが薬を飲みたくないと言っています。\nどうしますか？', '["無理に飲ませる","看護師に相談する","薬を捨てる","次の日に飲ませる"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Konsultasikan ke perawat.', true, NULL, E'服薬拒否の場面'),
  (E'📋 場面：夜勤中、利用者さんが眠れないと言っています。\nどうしますか？', '["睡眠薬を渡す","テレビをつける","話を聞いて安心させる","無視する"]'::jsonb, 2, 'jft', 'jft', 'situational', 3, E'Dengarkan dan tenangkan pasien.', true, NULL, E'夜間の不眠対応'),
  (E'📋 場面：利用者さんの家族が面会に来ました。\n何をしますか？', '["特に何もしない","利用者の様子を伝える","家族を帰す","薬を渡す"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Sampaikan kondisi pasien ke keluarga.', true, NULL, E'家族面会時の対応'),
  (E'📋 場面：車椅子からベッドに移乗します。\n正しい方法は？', '["一人で抱え上げる","ブレーキを確認し声かけしてから移乗","利用者に自分でやらせる","引きずって移動する"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Cek rem, beri instruksi, lalu transfer.', true, NULL, E'移乗介助の場面');
