-- Expanded exam question bank (idempotent)
-- N5: 30/section (90) | N4: 30/section (90) | JFT: 15/section (60)
-- Generated by scripts/generate-seed-sql.mjs (240 questions defined)

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.exam_questions
      WHERE exam_type = 'jlpt' AND level = 'n5' AND section = 'vocabulary' AND is_active = true) < 30 THEN
    INSERT INTO public.exam_questions
      (question_text, options, correct_answer, exam_type, level, section, difficulty, explanation, is_active, transcript, image_prompt)
    VALUES
  (E'「食べる」の読み方は？', '["たべる","のべる","くべる","しべる"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「食べる」dibaca たべる (taberu).', true, NULL, NULL),
  (E'「大きい」の意味は？', '["Small","Big","Fast","Slow"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「大きい」(ookii) berarti besar.', true, NULL, NULL),
  (E'「学校」の読み方は？', '["がくこう","がっこう","がくこ","がっこ"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「学校」dibaca がっこう (gakkou).', true, NULL, NULL),
  (E'「飲む」の意味は？', '["To eat","To sleep","To drink","To walk"]'::jsonb, 2, 'jlpt', 'n5', 'vocabulary', 3, E'「飲む」(nomu) berarti minum.', true, NULL, NULL),
  (E'「天気」の読み方は？', '["てんき","でんき","てんぎ","でんぎ"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「天気」dibaca てんき (tenki).', true, NULL, NULL),
  (E'「友達」の意味は？', '["Teacher","Student","Friend","Parent"]'::jsonb, 2, 'jlpt', 'n5', 'vocabulary', 3, E'「友達」(tomodachi) berarti teman.', true, NULL, NULL),
  (E'「書く」の読み方は？', '["かく","きく","けく","こく"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「書く」dibaca かく (kaku).', true, NULL, NULL),
  (E'「電車」の意味は？', '["Bus","Car","Bicycle","Train"]'::jsonb, 3, 'jlpt', 'n5', 'vocabulary', 3, E'「電車」(densha) berarti kereta.', true, NULL, NULL),
  (E'「朝」の読み方は？', '["よる","あさ","ひる","ゆう"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「朝」dibaca あさ (asa).', true, NULL, NULL),
  (E'「高い」の意味は？', '["Low","Cheap","Expensive/Tall","Short"]'::jsonb, 2, 'jlpt', 'n5', 'vocabulary', 3, E'「高い」(takai) berarti mahal/tinggi.', true, NULL, NULL),
  (E'「走る」の読み方は？', '["あるく","はしる","およぐ","とぶ"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「走る」dibaca はしる (hashiru).', true, NULL, NULL),
  (E'「病院」の意味は？', '["School","Hospital","Station","Library"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「病院」(byouin) berarti rumah sakit.', true, NULL, NULL),
  (E'「新しい」の読み方は？', '["あたらしい","ふるい","むずかしい","やさしい"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「新しい」dibaca あたらしい (atarashii).', true, NULL, NULL),
  (E'「仕事」の意味は？', '["Hobby","Work/Job","Study","Rest"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「仕事」(shigoto) berarti pekerjaan.', true, NULL, NULL),
  (E'「映画」の読み方は？', '["えが","えいが","えいか","えか"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「映画」dibaca えいが (eiga).', true, NULL, NULL),
  (E'「買う」の意味は？', '["To sell","To buy","To give","To receive"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「買う」(kau) berarti membeli.', true, NULL, NULL),
  (E'「入る」の読み方は？', '["はいる","でる","いる","おる"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「入る」dibaca はいる (hairu).', true, NULL, NULL),
  (E'「魚」の意味は？', '["Meat","Vegetable","Fruit","Fish"]'::jsonb, 3, 'jlpt', 'n5', 'vocabulary', 3, E'「魚」(sakana) berarti ikan.', true, NULL, NULL),
  (E'「寒い」の読み方は？', '["あつい","さむい","すずしい","あたたかい"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「寒い」dibaca さむい (samui).', true, NULL, NULL),
  (E'「窓」の意味は？', '["Door","Wall","Window","Floor"]'::jsonb, 2, 'jlpt', 'n5', 'vocabulary', 3, E'「窓」(mado) berarti jendela.', true, NULL, NULL),
  (E'「木」の読み方は？', '["き","もく","こ","ぼく"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「木」dibaca き (ki) sebagai kun-yomi.', true, NULL, NULL),
  (E'「川」の意味は？', '["Mountain","River","Lake","Sea"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「川」(kawa) berarti sungai.', true, NULL, NULL),
  (E'「口」の読み方は？', '["くち","ぐち","こう","ごう"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「口」dibaca くち (kuchi).', true, NULL, NULL),
  (E'「目」の意味は？', '["Ear","Nose","Eye","Mouth"]'::jsonb, 2, 'jlpt', 'n5', 'vocabulary', 3, E'「目」(me) berarti mata.', true, NULL, NULL),
  (E'「手」の読み方は？', '["て","しゅ","てまえ","しゅし"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「手」dibaca て (te).', true, NULL, NULL),
  (E'「足」の意味は？', '["Hand","Foot/Leg","Head","Body"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「足」(ashi) berarti kaki.', true, NULL, NULL),
  (E'「白い」の読み方は？', '["くろい","しろい","あかい","あおい"]'::jsonb, 1, 'jlpt', 'n5', 'vocabulary', 3, E'「白い」dibaca しろい (shiroi).', true, NULL, NULL),
  (E'「黒い」の意味は？', '["White","Red","Black","Blue"]'::jsonb, 2, 'jlpt', 'n5', 'vocabulary', 3, E'「黒い」(kuroi) berarti hitam.', true, NULL, NULL),
  (E'「暑い」の読み方は？', '["あつい","さむい","あたたかい","すずしい"]'::jsonb, 0, 'jlpt', 'n5', 'vocabulary', 3, E'「暑い」dibaca あつい (atsui) = panas.', true, NULL, NULL),
  (E'「涼しい」の意味は？', '["Hot","Cold","Cool","Warm"]'::jsonb, 2, 'jlpt', 'n5', 'vocabulary', 3, E'「涼しい」(suzushii) berarti sejuk.', true, NULL, NULL);
  END IF;
END $$;

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.exam_questions
      WHERE exam_type = 'jlpt' AND level = 'n5' AND section = 'grammar' AND is_active = true) < 30 THEN
    INSERT INTO public.exam_questions
      (question_text, options, correct_answer, exam_type, level, section, difficulty, explanation, is_active, transcript, image_prompt)
    VALUES
  (E'私＿学生です。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'Partikel は menandai topik kalimat.', true, NULL, NULL),
  (E'東京＿行きます。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Partikel に menandai tujuan pergerakan.', true, NULL, NULL),
  (E'水＿飲みます。', '["は","が","を","に"]'::jsonb, 2, 'jlpt', 'n5', 'grammar', 3, E'Partikel を menandai objek langsung.', true, NULL, NULL),
  (E'昨日、映画＿見ました。', '["は","が","を","に"]'::jsonb, 2, 'jlpt', 'n5', 'grammar', 3, E'Objek dari 見る adalah を.', true, NULL, NULL),
  (E'友達＿会いました。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'会う membutuhkan partikel に.', true, NULL, NULL),
  (E'ここ＿座ってください。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'座る di lokasi memakai に.', true, NULL, NULL),
  (E'日本語＿勉強します。', '["は","が","を","に"]'::jsonb, 2, 'jlpt', 'n5', 'grammar', 3, E'勉強する memakai を untuk objek.', true, NULL, NULL),
  (E'バス＿乗ります。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'乗る memakai に untuk alat transportasi.', true, NULL, NULL),
  (E'この本＿面白いです。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'Topik kalimat menggunakan は.', true, NULL, NULL),
  (E'猫＿います。', '["は","が","を","に"]'::jsonb, 1, 'jlpt', 'n5', 'grammar', 3, E'Keberadaan benda hidup memakai が.', true, NULL, NULL),
  (E'明日、学校＿行きません。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Tujuan pergerakan memakai に.', true, NULL, NULL),
  (E'コーヒー＿好きです。', '["は","が","を","に"]'::jsonb, 1, 'jlpt', 'n5', 'grammar', 3, E'好き memakai が untuk objek kesukaan.', true, NULL, NULL),
  (E'どこ＿行きますか。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Tujuan pertanyaan pergerakan memakai に.', true, NULL, NULL),
  (E'毎朝、六時＿起きます。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Waktu spesifik memakai に.', true, NULL, NULL),
  (E'これ＿何ですか。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'これ sebagai topik memakai は.', true, NULL, NULL),
  (E'田中さん＿先生です。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'Identitas topik memakai は.', true, NULL, NULL),
  (E'公園＿散歩します。', '["は","が","を","で"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Lokasi aktivitas memakai で.', true, NULL, NULL),
  (E'電車＿来ました。', '["は","が","を","に"]'::jsonb, 1, 'jlpt', 'n5', 'grammar', 3, E'Subjek aksi datang memakai が.', true, NULL, NULL),
  (E'夏＿暑いです。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'Musim sebagai topik memakai は.', true, NULL, NULL),
  (E'母＿料理を作ります。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'Pelaku sebagai topik memakai は.', true, NULL, NULL),
  (E'ペン＿貸してください。', '["は","が","を","に"]'::jsonb, 2, 'jlpt', 'n5', 'grammar', 3, E'貸す memakai を untuk objek.', true, NULL, NULL),
  (E'図書館＿本を読みます。', '["は","が","を","で"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Lokasi aktivitas memakai で.', true, NULL, NULL),
  (E'誰＿来ましたか。', '["は","が","を","に"]'::jsonb, 1, 'jlpt', 'n5', 'grammar', 3, E'Subjek pertanyaan memakai が.', true, NULL, NULL),
  (E'何＿食べますか。', '["は","が","を","に"]'::jsonb, 2, 'jlpt', 'n5', 'grammar', 3, E'Objek 食べる memakai を.', true, NULL, NULL),
  (E'いつ＿帰りますか。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'いつ sebagai topik memakai は.', true, NULL, NULL),
  (E'ここ＿写真を撮ってもいいですか。', '["は","が","を","で"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Lokasi memakai で.', true, NULL, NULL),
  (E'日本語＿話せますか。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n5', 'grammar', 3, E'Topik kemampuan memakai は.', true, NULL, NULL),
  (E'駅＿近くに住んでいます。', '["は","が","を","の"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Kepemilikan/lokasi memakai の.', true, NULL, NULL),
  (E'毎日、運動＿します。', '["は","が","を","に"]'::jsonb, 2, 'jlpt', 'n5', 'grammar', 3, E'する + objek memakai を.', true, NULL, NULL),
  (E'一緒＿食べましょう。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n5', 'grammar', 3, E'Bersama-sama memakai に.', true, NULL, NULL);
  END IF;
END $$;

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.exam_questions
      WHERE exam_type = 'jlpt' AND level = 'n5' AND section = 'reading' AND is_active = true) < 30 THEN
    INSERT INTO public.exam_questions
      (question_text, options, correct_answer, exam_type, level, section, difficulty, explanation, is_active, transcript, image_prompt)
    VALUES
  (E'「私は毎日学校に行きます。」— 私はどこに行きますか？', '["家","学校","会社","公園"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'学校 = sekolah.', true, NULL, NULL),
  (E'「田中さんは先生です。」— 田中さんの仕事は何ですか？', '["医者","先生","学生","会社員"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'先生 = guru.', true, NULL, NULL),
  (E'「今日は天気がいいです。」— 天気はどうですか？', '["悪い","いい","寒い","暑い"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'天気がいい = cuaca bagus.', true, NULL, NULL),
  (E'「猫が三匹います。」— 猫は何匹いますか？', '["一匹","二匹","三匹","四匹"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'三匹 = tiga ekor.', true, NULL, NULL),
  (E'「日曜日に映画を見ます。」— いつ映画を見ますか？', '["月曜日","水曜日","金曜日","日曜日"]'::jsonb, 3, 'jlpt', 'n5', 'reading', 3, E'日曜日 = hari Minggu.', true, NULL, NULL),
  (E'「この本は面白いです。」— 本はどうですか？', '["つまらない","難しい","面白い","簡単"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'面白い = menarik.', true, NULL, NULL),
  (E'「朝ごはんにパンを食べました。」— 何を食べましたか？', '["ご飯","パン","麺","お菓子"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'パン = roti.', true, NULL, NULL),
  (E'「駅まで歩いて10分です。」— 駅まで何分ですか？', '["5分","10分","15分","20分"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'10分 = sepuluh menit.', true, NULL, NULL),
  (E'「母は料理が上手です。」— 母は何が上手ですか？', '["掃除","料理","運動","歌"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'料理が上手 = pandai memasak.', true, NULL, NULL),
  (E'「来週、大阪に行きます。」— いつ行きますか？', '["今週","来週","先週","毎週"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'来週 = minggu depan.', true, NULL, NULL),
  (E'「弟は5歳です。」— 弟は何歳ですか？', '["3歳","4歳","5歳","6歳"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'5歳 = lima tahun.', true, NULL, NULL),
  (E'「図書館で本を借りました。」— どこで借りましたか？', '["本屋","学校","図書館","家"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'図書館 = perpustakaan.', true, NULL, NULL),
  (E'「夏休みに海に行きたいです。」— どこに行きたいですか？', '["山","海","川","湖"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'海 = laut.', true, NULL, NULL),
  (E'「この花は赤いです。」— 花は何色ですか？', '["白","青","赤","黄色"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'赤い = merah.', true, NULL, NULL),
  (E'「兄は大学生です。」— 兄は何をしていますか？', '["仕事","大学","高校","中学"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'大学生 = mahasiswa.', true, NULL, NULL),
  (E'「昨日、友達と遊びました。」— 誰と遊びましたか？', '["家族","先生","友達","一人"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'友達 = teman.', true, NULL, NULL),
  (E'「冬は寒いです。」— 冬はどうですか？', '["暑い","涼しい","暖かい","寒い"]'::jsonb, 3, 'jlpt', 'n5', 'reading', 3, E'寒い = dingin.', true, NULL, NULL),
  (E'「毎晩、9時に寝ます。」— 何時に寝ますか？', '["8時","9時","10時","11時"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'9時 = jam 9.', true, NULL, NULL),
  (E'「父は会社で働いています。」— 父はどこで働いていますか？', '["学校","病院","会社","店"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'会社 = perusahaan.', true, NULL, NULL),
  (E'「このケーキはおいしいです。」— ケーキはどうですか？', '["まずい","おいしい","甘くない","辛い"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'おいしい = enak.', true, NULL, NULL),
  (E'「私の趣味は音楽です。」— 趣味は何ですか？', '["スポーツ","音楽","読書","料理"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'趣味 = hobi.', true, NULL, NULL),
  (E'「電車で会社に行きます。」— 何で行きますか？', '["バス","車","電車","自転車"]'::jsonb, 2, 'jlpt', 'n5', 'reading', 3, E'電車 = kereta.', true, NULL, NULL),
  (E'「姉は医者です。」— 姉の仕事は？', '["先生","医者","看護師","会社員"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'医者 = dokter.', true, NULL, NULL),
  (E'「公園でサッカーをします。」— どこでサッカーをしますか？', '["学校","公園","家","海"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'公園 = taman.', true, NULL, NULL),
  (E'「毎週、日曜日に休みます。」— いつ休みますか？', '["月曜日","水曜日","金曜日","日曜日"]'::jsonb, 3, 'jlpt', 'n5', 'reading', 3, E'日曜日 = Minggu.', true, NULL, NULL),
  (E'「この店は安いです。」— 店はどうですか？', '["高い","安い","遠い","近い"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'安い = murah.', true, NULL, NULL),
  (E'「子供が二人います。」— 子供は何人いますか？', '["一人","二人","三人","四人"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'二人 = dua orang.', true, NULL, NULL),
  (E'「午後、買い物に行きます。」— いつ買い物に行きますか？', '["朝","午後","夜","深夜"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'午後 = sore/siang hari.', true, NULL, NULL),
  (E'「彼は背が高いです。」— 彼はどうですか？', '["低い","高い","太い","細い"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'背が高い = tinggi.', true, NULL, NULL),
  (E'「今日は仕事がありません。」— 今日はどうですか？', '["忙しい","暇","楽しい","悲しい"]'::jsonb, 1, 'jlpt', 'n5', 'reading', 3, E'仕事がない = senggang/ada waktu luang.', true, NULL, NULL);
  END IF;
END $$;

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.exam_questions
      WHERE exam_type = 'jlpt' AND level = 'n4' AND section = 'vocabulary' AND is_active = true) < 30 THEN
    INSERT INTO public.exam_questions
      (question_text, options, correct_answer, exam_type, level, section, difficulty, explanation, is_active, transcript, image_prompt)
    VALUES
  (E'「届ける」の意味は？', '["To receive","To deliver","To break","To forget"]'::jsonb, 1, 'jlpt', 'n4', 'vocabulary', 3, E'届ける (todokeru) = mengirimkan.', true, NULL, NULL),
  (E'「運ぶ」の読み方は？', '["はこぶ","もちぶ","かぶ","とぶ"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'運ぶ dibaca はこぶ (hakobu).', true, NULL, NULL),
  (E'「嬉しい」の意味は？', '["Sad","Happy","Angry","Tired"]'::jsonb, 1, 'jlpt', 'n4', 'vocabulary', 3, E'嬉しい (ureshii) = senang.', true, NULL, NULL),
  (E'「悲しい」の読み方は？', '["うれしい","かなしい","たのしい","さびしい"]'::jsonb, 1, 'jlpt', 'n4', 'vocabulary', 3, E'悲しい dibaca かなしい (kanashii).', true, NULL, NULL),
  (E'「疲れる」の意味は？', '["To rest","To get tired","To sleep","To work"]'::jsonb, 1, 'jlpt', 'n4', 'vocabulary', 3, E'疲れる (tsukareru) = lelah.', true, NULL, NULL),
  (E'「会議」の読み方は？', '["かいぎ","かいぎょう","かいけい","かいし"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'会議 dibaca かいぎ (kaigi).', true, NULL, NULL),
  (E'「遅れる」の意味は？', '["To hurry","To be late","To wait","To stop"]'::jsonb, 1, 'jlpt', 'n4', 'vocabulary', 3, E'遅れる (okureru) = terlambat.', true, NULL, NULL),
  (E'「準備」の読み方は？', '["じゅんび","じゅんじ","じゅんれい","じゅんかつ"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'準備 dibaca じゅんび (junbi).', true, NULL, NULL),
  (E'「経験」の意味は？', '["Experiment","Experience","Explanation","Expression"]'::jsonb, 1, 'jlpt', 'n4', 'vocabulary', 3, E'経験 (keiken) = pengalaman.', true, NULL, NULL),
  (E'「趣味」の読み方は？', '["しゅみ","しゅうみ","しゅぎ","しゅうぎ"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'趣味 dibaca しゅみ (shumi).', true, NULL, NULL),
  (E'「予定」の意味は？', '["Promise","Plan/Schedule","Prediction","Preparation"]'::jsonb, 1, 'jlpt', 'n4', 'vocabulary', 3, E'予定 (yotei) = rencana.', true, NULL, NULL),
  (E'「約束」の読み方は？', '["やくそく","やくわり","やくじん","やくめ"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'約束 dibaca やくそく (yakusoku).', true, NULL, NULL),
  (E'「心配」の意味は？', '["Care/ Worry","Heart","Mind","Trust"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'心配 (shinpai) = khawatir.', true, NULL, NULL),
  (E'「複雑」の読み方は？', '["ふくざつ","ふくせい","ふくごう","ふくそう"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'複雑 dibaca ふくざつ (fukuzatsu).', true, NULL, NULL),
  (E'「簡単」の意味は？', '["Difficult","Simple/Easy","Complex","Long"]'::jsonb, 1, 'jlpt', 'n4', 'vocabulary', 3, E'簡単 (kantan) = mudah.', true, NULL, NULL),
  (E'「必要」の読み方は？', '["ひつよう","ひつぜん","ひつじ","ひつぎ"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'必要 dibaca ひつよう (hitsuyou).', true, NULL, NULL),
  (E'「大切」の意味は？', '["Big","Important","Heavy","Expensive"]'::jsonb, 1, 'jlpt', 'n4', 'vocabulary', 3, E'大切 (taisetsu) = penting.', true, NULL, NULL),
  (E'「調べる」の読み方は？', '["しらべる","しらす","しらみ","しらが"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'調べる dibaca しらべる (shiraberu).', true, NULL, NULL),
  (E'「集める」の意味は？', '["To scatter","To collect","To throw","To divide"]'::jsonb, 1, 'jlpt', 'n4', 'vocabulary', 3, E'集める (atsumeru) = mengumpulkan.', true, NULL, NULL),
  (E'「続ける」の読み方は？', '["つづける","つける","つたえる","つくる"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'続ける dibaca つづける (tsuzukeru).', true, NULL, NULL),
  (E'「変える」の意味は？', '["To change","To return","To buy","To sell"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'変える (kaeru) = mengubah.', true, NULL, NULL),
  (E'「決める」の読み方は？', '["きめる","きめる","けめる","きる"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'決める dibaca きめる (kimeru).', true, NULL, NULL),
  (E'「間に合う」の意味は？', '["To be late","To be in time","To be early","To be absent"]'::jsonb, 1, 'jlpt', 'n4', 'vocabulary', 3, E'間に合う (maniau) = tepat waktu.', true, NULL, NULL),
  (E'「説明」の読み方は？', '["せつめい","せつりつ","せつだん","せつぞく"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'説明 dibaca せつめい (setsumei).', true, NULL, NULL),
  (E'「連絡」の意味は？', '["Connection/Contact","Transport","Translation","Collection"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'連絡 (renraku) = kontak.', true, NULL, NULL),
  (E'「留守」の読み方は？', '["るす","りゅうす","るし","りゅうし"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'留守 dibaca るす (rusu).', true, NULL, NULL),
  (E'「泳ぐ」の意味は？', '["To run","To swim","To jump","To fly"]'::jsonb, 1, 'jlpt', 'n4', 'vocabulary', 3, E'泳ぐ (oyogu) = berenang.', true, NULL, NULL),
  (E'「吸う」の読み方は？', '["すう","きゅう","しゅう","しょう"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'吸う dibaca すう (suu).', true, NULL, NULL),
  (E'「手伝う」の意味は？', '["To help","To carry","To wait","To teach"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'手伝う (tetsudau) = membantu.', true, NULL, NULL),
  (E'「具合」の読み方は？', '["ぐあい","くあい","ぐうあい","ぐわい"]'::jsonb, 0, 'jlpt', 'n4', 'vocabulary', 3, E'具合 dibaca ぐあい (guai) = kondisi.', true, NULL, NULL);
  END IF;
END $$;

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.exam_questions
      WHERE exam_type = 'jlpt' AND level = 'n4' AND section = 'grammar' AND is_active = true) < 30 THEN
    INSERT INTO public.exam_questions
      (question_text, options, correct_answer, exam_type, level, section, difficulty, explanation, is_active, transcript, image_prompt)
    VALUES
  (E'雨が降っ＿、傘を持って行きます。', '["た","て","る","ない"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'たら/て setelah hujan turun.', true, NULL, NULL),
  (E'本を読ん＿、寝ます。', '["だ","で","て","に"]'::jsonb, 1, 'jlpt', 'n4', 'grammar', 3, E'Vて、V = setelah membaca, tidur.', true, NULL, NULL),
  (E'日本語＿話せますか。', '["は","が","を","に"]'::jsonb, 1, 'jlpt', 'n4', 'grammar', 3, E'Kemampuan memakai が.', true, NULL, NULL),
  (E'この漢字＿読めますか。', '["は","が","を","に"]'::jsonb, 1, 'jlpt', 'n4', 'grammar', 3, E'可能形 + が untuk kemampuan.', true, NULL, NULL),
  (E'東京＿行きたいです。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n4', 'grammar', 3, E'行きたい + に untuk tujuan.', true, NULL, NULL),
  (E'寿司＿食べたいです。', '["は","が","を","に"]'::jsonb, 1, 'jlpt', 'n4', 'grammar', 3, E'食べたい + が untuk objek keinginan.', true, NULL, NULL),
  (E'京都＿大阪より静かです。', '["は","が","を","の"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'Perbandingan topik memakai は.', true, NULL, NULL),
  (E'バス＿電車より遅いです。', '["は","が","を","の"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'Topik perbandingan memakai は.', true, NULL, NULL),
  (E'早く起き＿、間に合いました。', '["たら","て","る","ない"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'たら = jika/setelah.', true, NULL, NULL),
  (E'安けれ＿、買います。', '["ば","たら","て","る"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'ければ/ば = kondisi.', true, NULL, NULL),
  (E'宿題をし＿、遊びに行きます。', '["ないで","なくて","ない","なく"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'ないで = tanpa melakukan.', true, NULL, NULL),
  (E'タバコを吸わ＿ください。', '["ないで","なくて","ない","なく"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'ないでください = jangan lakukan.', true, NULL, NULL),
  (E'彼＿会いたいです。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n4', 'grammar', 3, E'会う + に untuk orang.', true, NULL, NULL),
  (E'友達＿手紙を書きました。', '["は","が","に","へ"]'::jsonb, 2, 'jlpt', 'n4', 'grammar', 3, E'書く + に untuk penerima.', true, NULL, NULL),
  (E'先生＿質問しました。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n4', 'grammar', 3, E'質問する + に untuk orang.', true, NULL, NULL),
  (E'電車＿乗り換えます。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n4', 'grammar', 3, E'乗り換える + に.', true, NULL, NULL),
  (E'窓＿開けてください。', '["は","が","を","に"]'::jsonb, 2, 'jlpt', 'n4', 'grammar', 3, E'開ける + を.', true, NULL, NULL),
  (E'もっと勉強し＿、合格できます。', '["たら","て","れば","ない"]'::jsonb, 2, 'jlpt', 'n4', 'grammar', 3, E'ば/れば = jika lebih belajar.', true, NULL, NULL),
  (E'時間があれ＿、行きます。', '["ば","たら","て","る"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'あれば = jika ada waktu.', true, NULL, NULL),
  (E'仕事が終わっ＿、飲みに行きましょう。', '["たら","て","る","ない"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'たら = setelah selesai kerja.', true, NULL, NULL),
  (E'この本は面白く＿、読みました。', '["て","た","ない","る"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'Adjい→くて menghubungkan alasan.', true, NULL, NULL),
  (E'道が込んで＿、遅れました。', '["いて","いる","いた","いない"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'Vていて = karena sedang macet.', true, NULL, NULL),
  (E'彼女＿プレゼントをあげました。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n4', 'grammar', 3, E'あげる + に untuk penerima.', true, NULL, NULL),
  (E'母＿料理を教えてもらいました。', '["は","が","を","に"]'::jsonb, 3, 'jlpt', 'n4', 'grammar', 3, E'もらう + に untuk pemberi.', true, NULL, NULL),
  (E'図書館＿本を借りました。', '["は","が","を","で"]'::jsonb, 3, 'jlpt', 'n4', 'grammar', 3, E'Lokasi aktivitas memakai で.', true, NULL, NULL),
  (E'来週＿旅行に行きます。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'Waktu sebagai topik memakai は.', true, NULL, NULL),
  (E'毎日＿三時間勉強します。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'Durasi kebiasaan + は.', true, NULL, NULL),
  (E'彼＿知っていますか。', '["は","が","を","に"]'::jsonb, 0, 'jlpt', 'n4', 'grammar', 3, E'Topik pertanyaan memakai は.', true, NULL, NULL),
  (E'どちら＿好きですか。', '["は","が","を","に"]'::jsonb, 1, 'jlpt', 'n4', 'grammar', 3, E'好き + が.', true, NULL, NULL),
  (E'何＿買いましたか。', '["は","が","を","に"]'::jsonb, 2, 'jlpt', 'n4', 'grammar', 3, E'買う + を.', true, NULL, NULL);
  END IF;
END $$;

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.exam_questions
      WHERE exam_type = 'jlpt' AND level = 'n4' AND section = 'reading' AND is_active = true) < 30 THEN
    INSERT INTO public.exam_questions
      (question_text, options, correct_answer, exam_type, level, section, difficulty, explanation, is_active, transcript, image_prompt)
    VALUES
  (E'「田中さんは来週、大阪に出張します。三日間いません。」— 田中さんはいつ出張しますか？', '["今週","来週","先週","毎週"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'来週 = minggu depan.', true, NULL, NULL),
  (E'「田中さんは来週、大阪に出張します。三日間いません。」— 何日いませんか？', '["一日","二日","三日","四日"]'::jsonb, 2, 'jlpt', 'n4', 'reading', 3, E'三日間 = tiga hari.', true, NULL, NULL),
  (E'「昨日、雨が降ったので、傘を持って行きました。」— なぜ傘を持ちましたか？', '["暑いから","雨だから","風だから","雪だから"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'雨が降った = karena hujan.', true, NULL, NULL),
  (E'「このレストランは安くて、おいしいです。」— レストランはどうですか？', '["高くてまずい","安くておいしい","遠くて不便","新しくてきれい"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'安くておいしい = murah dan enak.', true, NULL, NULL),
  (E'「山田さんは毎朝、六時に起きて、ジョギングをします。」— 山田さんは何時に起きますか？', '["五時","六時","七時","八時"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'六時 = jam 6.', true, NULL, NULL),
  (E'「山田さんは毎朝、六時に起きて、ジョギングをします。」— 朝、何をしますか？', '["散歩","ジョギング","泳ぐ","読書"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'ジョギング = jogging.', true, NULL, NULL),
  (E'「来月、友達の結婚式があります。プレゼントを買います。」— 何を買いますか？', '["服","プレゼント","花","ケーキ"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'プレゼント untuk pernikahan.', true, NULL, NULL),
  (E'「電車が遅れたので、会議に遅れました。」— なぜ遅れましたか？', '["電車が遅れた","寝坊した","道に迷った","病気だ"]'::jsonb, 0, 'jlpt', 'n4', 'reading', 3, E'電車が遅れた = kereta terlambat.', true, NULL, NULL),
  (E'「夏休みに海に行きたいです。泳ぎたいです。」— 何をしたいですか？', '["山に登る","泳ぐ","スキー","釣り"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'泳ぎたい = ingin berenang.', true, NULL, NULL),
  (E'「この仕事は難しいですが、面白いです。」— 仕事はどうですか？', '["簡単でつまらない","難しいが面白い","簡単で楽しい","難しくて疲れる"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'難しいが面白い.', true, NULL, NULL),
  (E'「佐藤さんは日本語が上手です。毎日勉強しています。」— 佐藤さんは何が上手ですか？', '["英語","日本語","数学","料理"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'日本語が上手.', true, NULL, NULL),
  (E'「駅から歩いて十五分です。バスもあります。」— 駅から何分ですか？', '["五分","十分","十五分","二十分"]'::jsonb, 2, 'jlpt', 'n4', 'reading', 3, E'十五分 = 15 menit.', true, NULL, NULL),
  (E'「明日の天気は雨です。傘を忘れないでください。」— 明日の天気は？', '["晴れ","雨","雪","曇り"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'雨 = hujan.', true, NULL, NULL),
  (E'「母の誕生日に花を贈りました。とても喜びました。」— 何を贈りましたか？', '["ケーキ","花","服","本"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'花 = bunga.', true, NULL, NULL),
  (E'「新しいパソコンを買いました。仕事が楽になりました。」— 何を買いましたか？', '["車","パソコン","テレビ","カメラ"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'パソコン = komputer.', true, NULL, NULL),
  (E'「彼は毎週、土曜日にボランティアをしています。」— いつボランティアをしますか？', '["金曜日","土曜日","日曜日","月曜日"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'土曜日 = Sabtu.', true, NULL, NULL),
  (E'「この薬は食後に飲んでください。一日三回です。」— 一日何回ですか？', '["一回","二回","三回","四回"]'::jsonb, 2, 'jlpt', 'n4', 'reading', 3, E'三回 = tiga kali.', true, NULL, NULL),
  (E'「会議は三時から五時までです。二時間です。」— 会議は何時間ですか？', '["一時間","二時間","三時間","四時間"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'二時間 = dua jam.', true, NULL, NULL),
  (E'「彼女はピアノが弾けます。子供の時から習っています。」— 彼女は何ができますか？', '["歌","ピアノ","ダンス","絵"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'ピアノが弾ける.', true, NULL, NULL),
  (E'「来週のテストのために、毎日復習しています。」— 何のために復習していますか？', '["面接","テスト","旅行","パーティー"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'テスト = ujian.', true, NULL, NULL),
  (E'「この道をまっすぐ行って、右に曲がってください。」— どこに曲がりますか？', '["左","右","前","後"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'右に曲がる = belok kanan.', true, NULL, NULL),
  (E'「荷物が重いので、タクシーに乗りました。」— なぜタクシーに乗りましたか？', '["安いから","速いから","重いから","近いから"]'::jsonb, 2, 'jlpt', 'n4', 'reading', 3, E'荷物が重い = barang berat.', true, NULL, NULL),
  (E'「彼は風邪をひいたので、今日は休みます。」— 彼はどうしましたか？', '["風邪","怪我","頭痛","腹痛"]'::jsonb, 0, 'jlpt', 'n4', 'reading', 3, E'風邪をひく = masuk angin.', true, NULL, NULL),
  (E'「この店は人気があります。いつも込んでいます。」— 店はどうですか？', '["空いている","込んでいる","閉まっている","新しい"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'込んでいる = ramai/penuh.', true, NULL, NULL),
  (E'「来月、引っ越しします。新しいアパートに住みます。」— 来月、何をしますか？', '["旅行","引っ越し","結婚","就職"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'引っ越し = pindah rumah.', true, NULL, NULL),
  (E'「彼は英語もフランス語も話せます。三か国語です。」— 何か国語話せますか？', '["一","二","三","四"]'::jsonb, 2, 'jlpt', 'n4', 'reading', 3, E'三か国語 = tiga bahasa.', true, NULL, NULL),
  (E'「試験に合格したので、家族に報告しました。」— 何をしましたか？', '["報告","相談","謝罪","依頼"]'::jsonb, 0, 'jlpt', 'n4', 'reading', 3, E'報告 = melaporkan.', true, NULL, NULL),
  (E'「この問題は難しすぎます。先生に聞きます。」— どうしますか？', '["諦める","先生に聞く","友達に聞く","本で調べる"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'先生に聞く.', true, NULL, NULL),
  (E'「電話が鳴ったので、出ました。母でした。」— 誰の電話でしたか？', '["友達","母","先生","会社"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'母 = ibu.', true, NULL, NULL),
  (E'「今日は早く帰りたいです。用事があります。」— なぜ早く帰りたいですか？', '["疲れた","用事がある","病気だ","天気が悪い"]'::jsonb, 1, 'jlpt', 'n4', 'reading', 3, E'用事がある = ada urusan.', true, NULL, NULL);
  END IF;
END $$;

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.exam_questions
      WHERE exam_type = 'jft' AND level = 'jft' AND section = 'kanji_reading' AND is_active = true) < 15 THEN
    INSERT INTO public.exam_questions
      (question_text, options, correct_answer, exam_type, level, section, difficulty, explanation, is_active, transcript, image_prompt)
    VALUES
  (E'「介護」の読み方は？', '["かいご","かいこ","けいご","けいこ"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「介護」dibaca かいご (kaigo).', true, NULL, NULL),
  (E'「患者」の読み方は？', '["かんしゃ","かんじゃ","がんしゃ","がんじゃ"]'::jsonb, 1, 'jft', 'jft', 'kanji_reading', 3, E'「患者」dibaca かんじゃ (kanja).', true, NULL, NULL),
  (E'「食事」の読み方は？', '["しょくじ","しょくし","しゅくじ","しゅくし"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「食事」dibaca しょくじ (shokuji).', true, NULL, NULL),
  (E'「体温」の読み方は？', '["たいおん","ていおん","たいうん","ていうん"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「体温」dibaca たいおん (taion).', true, NULL, NULL),
  (E'「血圧」の読み方は？', '["けつあつ","ちあつ","けちあつ","ちけつ"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「血圧」dibaca けつあつ (ketsuatsu).', true, NULL, NULL),
  (E'「入浴」の読み方は？', '["にゅうよく","いりよく","にゅうあび","いりあび"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「入浴」dibaca にゅうよく (nyuuyoku).', true, NULL, NULL),
  (E'「排泄」の読み方は？', '["はいせつ","はいさつ","ばいせつ","ばいさつ"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「排泄」dibaca はいせつ (haisetsu).', true, NULL, NULL),
  (E'「服薬」の読み方は？', '["ふくやく","ふくぐすり","はくやく","はくぐすり"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「服薬」dibaca ふくやく (fukuyaku).', true, NULL, NULL),
  (E'「記録」の読み方は？', '["きろく","ぎろく","きりょく","ぎりょく"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「記録」dibaca きろく (kiroku).', true, NULL, NULL),
  (E'「症状」の読み方は？', '["しょうじょう","せいじょう","しょうそう","せいそう"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'「症状」dibaca しょうじょう (shoujou).', true, NULL, NULL),
  (E'「転倒」の読み方は？', '["てんとう","てんどう","でんとう","でんどう"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'転倒 dibaca てんとう (tentou).', true, NULL, NULL),
  (E'「誤嚥」の読み方は？', '["ごえん","ごいん","こえん","こいん"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'誤嚥 dibaca ごえん (goen).', true, NULL, NULL),
  (E'「褥瘡」の読み方は？', '["じょくそう","じょくぞう","しょくそう","しょくぞう"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'褥瘡 dibaca じょくそう (jokusou).', true, NULL, NULL),
  (E'「清拭」の読み方は？', '["せいしき","せいしゅう","しょうしき","しょうしゅう"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'清拭 dibaca せいしき (seishiki).', true, NULL, NULL),
  (E'「移乗」の読み方は？', '["いじょう","いしょう","いそう","いじゅう"]'::jsonb, 0, 'jft', 'jft', 'kanji_reading', 3, E'移乗 dibaca いじょう (ijou).', true, NULL, NULL);
  END IF;
END $$;

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.exam_questions
      WHERE exam_type = 'jft' AND level = 'jft' AND section = 'vocabulary' AND is_active = true) < 15 THEN
    INSERT INTO public.exam_questions
      (question_text, options, correct_answer, exam_type, level, section, difficulty, explanation, is_active, transcript, image_prompt)
    VALUES
  (E'「バイタル」とは何ですか？', '["生命徴候","薬の名前","食事の種類","運動の方法"]'::jsonb, 0, 'jft', 'jft', 'vocabulary', 3, E'バイタル = tanda-tanda vital.', true, NULL, NULL),
  (E'「おむつ交換」の意味は？', '["シーツを替える","おむつを替える","服を替える","靴を替える"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'おむつ交換 = ganti popok.', true, NULL, NULL),
  (E'「車椅子」の読み方は？', '["くるまいす","しゃいす","くるまかご","しゃかご"]'::jsonb, 0, 'jft', 'jft', 'vocabulary', 3, E'「車椅子」dibaca くるまいす (kurumaisu).', true, NULL, NULL),
  (E'「寝返り」の意味は？', '["起きること","寝ること","体の向きを変えること","歩くこと"]'::jsonb, 2, 'jft', 'jft', 'vocabulary', 3, E'寝返り = membalik badan.', true, NULL, NULL),
  (E'「誤嚥」の意味は？', '["食べ過ぎ","飲み込み間違い","アレルギー反応","消化不良"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'誤嚥 = salah menelan.', true, NULL, NULL),
  (E'「褥瘡」とは？', '["骨折","床ずれ","やけど","切り傷"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'褥瘡 = luka tekan (bedsore).', true, NULL, NULL),
  (E'「利用者」の意味は？', '["スタッフ","ケアを受ける人","医者","看護師"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'利用者 = pengguna layanan/pasien.', true, NULL, NULL),
  (E'「申し送り」の意味は？', '["手紙を送る","引き継ぎ報告","買い物リスト","休憩時間"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'申し送り = serah terima/shift report.', true, NULL, NULL),
  (E'「清拭」の意味は？', '["掃除すること","体を拭くこと","洗濯すること","料理すること"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'清拭 = membersihkan tubuh.', true, NULL, NULL),
  (E'「移乗」の意味は？', '["電車に乗る","ベッドから車椅子へ移ること","引っ越し","旅行"]'::jsonb, 1, 'jft', 'jft', 'vocabulary', 3, E'移乗 = transfer (bed ke kursi roda).', true, NULL, NULL),
  (E'「ナースコール」とは？', '["呼び出しベル","薬の名前","食事の時間","入浴の道具"]'::jsonb, 0, 'jft', 'jft', 'vocabulary', 3, E'ナースコール = bell panggilan perawat.', true, NULL, NULL),
  (E'「見守り」の意味は？', '["監視・世話","睡眠","運動","食事"]'::jsonb, 0, 'jft', 'jft', 'vocabulary', 3, E'見守り = mengawasi/menemani.', true, NULL, NULL),
  (E'「介助」の読み方は？', '["かいじょ","かいじょ","かいしょ","かいじゅ"]'::jsonb, 0, 'jft', 'jft', 'vocabulary', 3, E'介助 dibaca かいじょ (kaijo).', true, NULL, NULL),
  (E'「自立」の意味は？', '["Mandiri","Bantuan","Istirahat","Perawatan"]'::jsonb, 0, 'jft', 'jft', 'vocabulary', 3, E'自立 (jiritsu) = mandiri.', true, NULL, NULL),
  (E'「リハビリ」の意味は？', '["Rehabilitasi","Rekreasi","Resep","Reservasi"]'::jsonb, 0, 'jft', 'jft', 'vocabulary', 3, E'リハビリ = rehabilitasi.', true, NULL, NULL);
  END IF;
END $$;

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.exam_questions
      WHERE exam_type = 'jft' AND level = 'jft' AND section = 'conversation' AND is_active = true) < 15 THEN
    INSERT INTO public.exam_questions
      (question_text, options, correct_answer, exam_type, level, section, difficulty, explanation, is_active, transcript, image_prompt)
    VALUES
  (E'🔊 「すみません、お水をもらえますか。」\n— 利用者さんは何を求めていますか？', '["食事","水","薬","トイレ"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'利用者 meminta air.', true, E'利用者：すみません、お水をもらえますか。\n介護士：はい、少々お待ちください。', NULL),
  (E'🔊 「今日は調子がいいです。」\n— 利用者さんの体調は？', '["悪い","普通","良い","わからない"]'::jsonb, 2, 'jft', 'jft', 'conversation', 3, E'Kondisi pasien baik hari ini.', true, E'介護士：今日のご気分はいかがですか？\n利用者：今日は調子がいいです。', NULL),
  (E'🔊 「少し寒いです。」\n— 何をすべきですか？', '["窓を開ける","エアコンを下げる","毛布をかける","水を持っていく"]'::jsonb, 2, 'jft', 'jft', 'conversation', 3, E'Pasien merasa dingin, beri selimut.', true, E'利用者：少し寒いです。\n介護士：毛布をお持ちしますね。', NULL),
  (E'🔊 「頭が痛いです。」\n— 利用者さんの症状は？', '["腹痛","頭痛","腰痛","歯痛"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Gejala: sakit kepala.', true, E'利用者：頭が痛いです。\n介護士：看護師に伝えますね。', NULL),
  (E'🔊 「トイレに行きたいです。」\n— 利用者さんは何をしたいですか？', '["食事","散歩","トイレ","入浴"]'::jsonb, 2, 'jft', 'jft', 'conversation', 3, E'Pasien ingin ke toilet.', true, E'利用者：トイレに行きたいです。\n介護士：お手伝いしますね。', NULL),
  (E'🔊 「お薬の時間ですよ。」\n— 介護士は何をしていますか？', '["食事の準備","服薬の案内","入浴の準備","体操の案内"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Pengingat waktu minum obat.', true, E'介護士：○○さん、お薬の時間ですよ。\n利用者：ありがとうございます。', NULL),
  (E'🔊 「腰が痛いので、ゆっくりお願いします。」\n— 何に注意すべきですか？', '["速く動く","ゆっくり動く","動かない","走る"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Gerakkan pasien perlahan.', true, E'利用者：腰が痛いので、ゆっくりお願いします。\n介護士：はい、ゆっくりしましょうね。', NULL),
  (E'🔊 「ご飯はもういらないです。」\n— 利用者さんは？', '["もっと食べたい","食事を終えたい","飲み物が欲しい","デザートが欲しい"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Pasien sudah selesai makan.', true, E'介護士：もう少し食べますか？\n利用者：ご飯はもういらないです。', NULL),
  (E'🔊 「散歩に行きましょうか。」\n— 介護士は何を提案していますか？', '["食事","入浴","散歩","睡眠"]'::jsonb, 2, 'jft', 'jft', 'conversation', 3, E'Caregiver mengajak jalan-jalan.', true, E'介護士：天気がいいですね。散歩に行きましょうか。\n利用者：はい、行きたいです。', NULL),
  (E'🔊 「夜、よく眠れましたか。」\n— 介護士は何を聞いていますか？', '["食事","睡眠","排泄","体温"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Menanyakan kualitas tidur malam.', true, E'介護士：おはようございます。夜、よく眠れましたか？\n利用者：はい、ぐっすり眠れました。', NULL),
  (E'🔊 「お腹が痛いです。」\n— 利用者さんの症状は？', '["頭痛","腹痛","腰痛","歯痛"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'お腹が痛い = sakit perut.', true, E'利用者：お腹が痛いです。\n介護士：看護師に伝えますね。', NULL),
  (E'🔊 「もう少し食べられますか。」\n— 介護士は何を聞いていますか？', '["飲み物","食事","薬","睡眠"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Menanyakan apakah masih bisa makan.', true, E'介護士：もう少し食べられますか。\n利用者：はい、少しなら。', NULL),
  (E'🔊 「お風呂に入りたいです。」\n— 利用者さんは何をしたいですか？', '["食事","入浴","散歩","睡眠"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Ingin mandi.', true, E'利用者：お風呂に入りたいです。\n介護士：準備しますね。', NULL),
  (E'🔊 「息が苦しいです。」\n— 何をすべきですか？', '["無視する","すぐに報告する","散歩に連れる","食事を出す"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Sesak napas = laporkan segera.', true, E'利用者：息が苦しいです。\n介護士：すぐに看護師を呼びます。', NULL),
  (E'🔊 「ありがとうございます。」\n— 利用者さんは何をしていますか？', '["謝る","感謝する","怒る","頼む"]'::jsonb, 1, 'jft', 'jft', 'conversation', 3, E'Mengucapkan terima kasih.', true, E'介護士：お手伝いしました。\n利用者：ありがとうございます。', NULL);
  END IF;
END $$;

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM public.exam_questions
      WHERE exam_type = 'jft' AND level = 'jft' AND section = 'situational' AND is_active = true) < 15 THEN
    INSERT INTO public.exam_questions
      (question_text, options, correct_answer, exam_type, level, section, difficulty, explanation, is_active, transcript, image_prompt)
    VALUES
  (E'📋 場面：利用者さんが転倒しました。\n最初に何をしますか？', '["すぐに起こす","安全を確認して声をかける","他の利用者に伝える","記録を書く"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Prioritas: pastikan keamanan pasien.', true, NULL, E'利用者が廊下で転倒した場面'),
  (E'📋 場面：利用者さんが「帰りたい」と言っています。\nどう対応しますか？', '["「帰れません」と言う","無視する","気持ちを聞いて寄り添う","家族に電話する"]'::jsonb, 2, 'jft', 'jft', 'situational', 3, E'Dengarkan dan dampingi perasaan pasien.', true, NULL, E'認知症の利用者が帰宅願望を示す場面'),
  (E'📋 場面：食事中に利用者さんがむせました。\nどうしますか？', '["水を飲ませる","食事を続ける","背中をさすって様子を見る","すぐに救急車を呼ぶ"]'::jsonb, 2, 'jft', 'jft', 'situational', 3, E'Tepuk punggung dan pantau kondisi.', true, NULL, E'食事介助中にむせた場面'),
  (E'📋 場面：利用者さんの顔色が悪いです。\n何をしますか？', '["そのまま様子を見る","バイタルを測定し報告する","食事を提供する","散歩に連れ出す"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Ukur vital sign dan laporkan.', true, NULL, E'利用者の体調変化に気づいた場面'),
  (E'📋 場面：他の介護士が休憩中です。ナースコールが鳴りました。\nどうしますか？', '["休憩中の人を呼ぶ","無視する","自分が対応する","後で対応する"]'::jsonb, 2, 'jft', 'jft', 'situational', 3, E'Tanggapi panggilan segera.', true, NULL, E'人手不足時のナースコール対応'),
  (E'📋 場面：入浴中に利用者さんが「熱い」と言いました。\nどうしますか？', '["我慢してもらう","すぐに温度を下げる","入浴を中止する","水を追加する"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Turunkan suhu air mandi.', true, NULL, E'入浴介助中の温度調整'),
  (E'📋 場面：利用者さんが薬を飲みたくないと言っています。\nどうしますか？', '["無理に飲ませる","看護師に相談する","薬を捨てる","次の日に飲ませる"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Konsultasikan ke perawat.', true, NULL, E'服薬拒否の場面'),
  (E'📋 場面：夜勤中、利用者さんが眠れないと言っています。\nどうしますか？', '["睡眠薬を渡す","テレビをつける","話を聞いて安心させる","無視する"]'::jsonb, 2, 'jft', 'jft', 'situational', 3, E'Dengarkan dan tenangkan pasien.', true, NULL, E'夜間の不眠対応'),
  (E'📋 場面：利用者さんの家族が面会に来ました。\n何をしますか？', '["特に何もしない","利用者の様子を伝える","家族を帰す","薬を渡す"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Sampaikan kondisi pasien ke keluarga.', true, NULL, E'家族面会時の対応'),
  (E'📋 場面：車椅子からベッドに移乗します。\n正しい方法は？', '["一人で抱え上げる","ブレーキを確認し声かけしてから移乗","利用者に自分でやらせる","引きずって移動する"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Cek rem, beri instruksi, lalu transfer.', true, NULL, E'移乗介助の場面'),
  (E'📋 場面：利用者さんが食事を残しました。\nどうしますか？', '["無理に食べさせる","理由を聞いて記録する","無視する","捨てる"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Tanyakan alasan dan catat.', true, NULL, E'食事を残した場面'),
  (E'📋 場面：利用者さんが他の利用者と喧嘩しました。\nどうしますか？', '["大声で叱る","双方を隔離し報告する","無視する","罰を与える"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Pisahkan dan laporkan.', true, NULL, E'利用者間のトラブル'),
  (E'📋 場面：利用者さんが歩行器を使っています。\n注意することは？', '["走らせる","ゆっくり付き添う","離れる","奪う"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Dampingi dengan perlahan.', true, NULL, E'歩行器介助'),
  (E'📋 場面：利用者さんが認知症で同じ質問を繰り返します。\nどうしますか？', '["イライラする","何度も丁寧に答える","無視する","部屋を出る"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Jawab dengan sabar berulang kali.', true, NULL, E'認知症の利用者'),
  (E'📋 場面：利用者さんの褥瘡を発見しました。\nどうしますか？', '["そのままにする","体位変換し看護師に報告","自分で治療する","隠す"]'::jsonb, 1, 'jft', 'jft', 'situational', 3, E'Ganti posisi dan laporkan.', true, NULL, E'褥瘡発見の場面');
  END IF;
END $$;
